<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Models\Form;
use App\Models\FormMetadata\FormSoftwareSource;
use App\Models\FormMetadata\FormLocation;
use App\Models\FormMetadata\UserType;

/**
 * This seeder is designed to perform bulk updates on form metadata, specifically for software sources, locations, and user types.
 * It uses `form_id` and `name` columns instead of IDs to ensure that the updates are applied correctly, even if the IDs in the database have changed.
 * Check laravel.log for any warnings about mismatches between the spreadsheet and the database. 
 * See ADO#4146 (https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/4146/) for the source of the data.
 */
class BulkFormMetadataUpdateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // ========================================================================
        // 1. SOFTWARE SOURCE UPDATES
        // ========================================================================

        Log::warning("BulkMetadataUpdateSeeder: Beginning bulk update of form software sources...");

        $softwareSourceUpdates = [
            ['form_id' => 'HR3740E', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3740F', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3741', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3681', 'name' => 'Unknown'],
            ['form_id' => 'HR3691F', 'name' => 'Unknown'],
            ['form_id' => 'HR3704F', 'name' => 'Unknown'],
            ['form_id' => 'HR4008', 'name' => 'Unknown'],
            ['form_id' => 'HR3689E', 'name' => 'Unknown'],
            ['form_id' => 'HR3687E-AT', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATa', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATb', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATd', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATf', 'name' => 'Unknown'],
            ['form_id' => 'HR3260', 'name' => 'Adobe'],
            ['form_id' => 'HR3599', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3219', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3262', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3534', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3233', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3236', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3249', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3334', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3335', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3555', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3633', 'name' => 'Unknown'],
            ['form_id' => 'HR2247', 'name' => 'Unknown'],
            ['form_id' => 'HR2766', 'name' => 'Unknown'],
            ['form_id' => 'HR3352F', 'name' => 'Unknown'],
            ['form_id' => 'HR3353F', 'name' => 'Unknown'],
            ['form_id' => 'HR3354F', 'name' => 'Unknown'],
            ['form_id' => 'HR3355F', 'name' => 'Unknown'],
            ['form_id' => 'HR3356F', 'name' => 'Unknown'],
            ['form_id' => 'HR3357F', 'name' => 'Unknown'],
            ['form_id' => 'HR3358F', 'name' => 'Unknown'],
            ['form_id' => 'HR3360F', 'name' => 'Unknown'],
            ['form_id' => 'HR3361F', 'name' => 'Unknown'],
            ['form_id' => 'HR3362F', 'name' => 'Unknown'],
            ['form_id' => 'HR3363F', 'name' => 'Unknown'],
            ['form_id' => 'HR3364F', 'name' => 'Unknown'],
            ['form_id' => 'HR3365F', 'name' => 'Unknown'],
            ['form_id' => 'HR3366F', 'name' => 'Unknown'],
            ['form_id' => 'HR3367F', 'name' => 'Unknown'],
            ['form_id' => 'HR3368F', 'name' => 'Unknown'],
            ['form_id' => 'HR3369F', 'name' => 'Unknown'],
            ['form_id' => 'HR3370F', 'name' => 'Unknown'],
            ['form_id' => 'HR3372F', 'name' => 'Unknown'],
            ['form_id' => 'HR3376F', 'name' => 'Unknown'],
            ['form_id' => 'HR3379F', 'name' => 'Unknown'],
            ['form_id' => 'HR3380F', 'name' => 'Unknown'],
            ['form_id' => 'HR3381F', 'name' => 'Unknown'],
            ['form_id' => 'HR3382F', 'name' => 'Unknown'],
            ['form_id' => 'HR3383F', 'name' => 'Unknown'],
            ['form_id' => 'HR3384F', 'name' => 'Unknown'],
            ['form_id' => 'HR3385F', 'name' => 'Unknown'],
            ['form_id' => 'HR3386F', 'name' => 'Unknown'],
            ['form_id' => 'HR3387F', 'name' => 'Unknown'],
            ['form_id' => 'HR3388F', 'name' => 'Unknown'],
            ['form_id' => 'HR3389F', 'name' => 'Unknown'],
            ['form_id' => 'HR3390F', 'name' => 'Unknown'],
            ['form_id' => 'HR3391F', 'name' => 'Unknown'],
            ['form_id' => 'HR3392F', 'name' => 'Unknown'],
            ['form_id' => 'HR3393F', 'name' => 'Unknown'],
            ['form_id' => 'HR3394F', 'name' => 'Unknown'],
            ['form_id' => 'HR3396F', 'name' => 'Unknown'],
            ['form_id' => 'HR3397F', 'name' => 'Unknown'],
            ['form_id' => 'HR3398F', 'name' => 'Unknown'],
            ['form_id' => 'HR3399F', 'name' => 'Unknown'],
            ['form_id' => 'HR3400F', 'name' => 'Unknown'],
            ['form_id' => 'HR3450F', 'name' => 'Unknown'],
            ['form_id' => 'HR3451F', 'name' => 'Unknown'],
            ['form_id' => 'HR3452F', 'name' => 'Unknown'],
            ['form_id' => 'HR3453F', 'name' => 'Unknown'],
            ['form_id' => 'HR3454F', 'name' => 'Unknown'],
            ['form_id' => 'HR3455F', 'name' => 'Unknown'],
            ['form_id' => 'HR3456F', 'name' => 'Unknown'],
            ['form_id' => 'HR3458F', 'name' => 'Unknown'],
            ['form_id' => 'HR3459F', 'name' => 'Unknown'],
            ['form_id' => 'HR3484F', 'name' => 'Unknown'],
            ['form_id' => 'HR3688F', 'name' => 'Unknown'],
            ['form_id' => 'HR3692F', 'name' => 'Unknown'],
            ['form_id' => 'HR3693F', 'name' => 'Unknown'],
            ['form_id' => 'HR3694F', 'name' => 'Unknown'],
            ['form_id' => 'HR3695F', 'name' => 'Unknown'],
            ['form_id' => 'HR3696F', 'name' => 'Unknown'],
            ['form_id' => 'HR3698E-AT', 'name' => 'Unknown'],
            ['form_id' => 'HR3698F', 'name' => 'Unknown'],
            ['form_id' => 'HR3699F', 'name' => 'Unknown'],
            ['form_id' => 'HR3700F', 'name' => 'Unknown'],
            ['form_id' => 'HR3701F', 'name' => 'Unknown'],
            ['form_id' => 'HR3702F', 'name' => 'Unknown'],
            ['form_id' => 'HR3703F', 'name' => 'Unknown'],
            ['form_id' => 'HR3710F', 'name' => 'Unknown'],
            ['form_id' => 'HR3655E', 'name' => 'Unknown'],
            ['form_id' => 'CF0605_portal', 'name' => 'Unknown'],
            ['form_id' => 'HR3492E', 'name' => 'Unknown'],
            ['form_id' => 'HR3600', 'name' => 'Unknown'],
            ['form_id' => 'HR3601E', 'name' => 'Unknown'],
            ['form_id' => 'HR3602', 'name' => 'Unknown'],
            ['form_id' => 'HR3603', 'name' => 'Unknown'],
            ['form_id' => 'HR3604', 'name' => 'Unknown'],
            ['form_id' => 'HR3605', 'name' => 'Unknown'],
            ['form_id' => 'HR3606', 'name' => 'Unknown'],
            ['form_id' => 'HR3607', 'name' => 'Unknown'],
            ['form_id' => 'HR3608', 'name' => 'Unknown'],
            ['form_id' => 'HR3609', 'name' => 'Unknown'],
            ['form_id' => 'HR3610', 'name' => 'Unknown'],
            ['form_id' => 'HR3611', 'name' => 'Unknown'],
            ['form_id' => 'HR3612', 'name' => 'Unknown'],
            ['form_id' => 'HR3613', 'name' => 'Unknown'],
            ['form_id' => 'HR3654E', 'name' => 'Unknown'],
            ['form_id' => 'HR3671', 'name' => 'Unknown'],
            ['form_id' => 'HR3711', 'name' => 'Unknown'],
            ['form_id' => 'HR3714E', 'name' => 'Unknown'],
            ['form_id' => 'MW-001', 'name' => 'Unknown'],
            ['form_id' => 'HR3488E', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3499E', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3527E', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3589A', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3589B', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3589C', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3653E', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3678B', 'name' => 'Adobe Livecycle'],
            ['form_id' => 'HR3259', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3322', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3347', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3348', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3349', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3476', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3478', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3479', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3480', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3481', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3482', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3491', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3537', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3538', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR3539', 'name' => 'Microsoft Word'],
            ['form_id' => 'HR2152', 'name' => 'Unknown'],
            ['form_id' => 'HR2181A', 'name' => 'Unknown'],
            ['form_id' => 'HR2181B', 'name' => 'Unknown'],
            ['form_id' => 'HR2181C', 'name' => 'Unknown'],
            ['form_id' => 'HR2192', 'name' => 'Unknown'],
            ['form_id' => 'HR2193', 'name' => 'Unknown'],
            ['form_id' => 'HR2274', 'name' => 'Unknown'],
            ['form_id' => 'HR2340', 'name' => 'Unknown'],
            ['form_id' => 'HR2365', 'name' => 'Unknown'],
            ['form_id' => 'HR2366', 'name' => 'Unknown'],
            ['form_id' => 'HR2368', 'name' => 'Unknown'],
            ['form_id' => 'HR2527', 'name' => 'Unknown'],
            ['form_id' => 'HR2545', 'name' => 'Unknown'],
            ['form_id' => 'HR2609', 'name' => 'Unknown'],
            ['form_id' => 'HR2663B', 'name' => 'Unknown'],
            ['form_id' => 'HR2674', 'name' => 'Unknown'],
            ['form_id' => 'HR2754', 'name' => 'Unknown'],
            ['form_id' => 'HR2767', 'name' => 'Unknown'],
            ['form_id' => 'HR2778', 'name' => 'Unknown'],
            ['form_id' => 'HR2781', 'name' => 'Unknown'],
            ['form_id' => 'HR2791', 'name' => 'Unknown'],
            ['form_id' => 'HR2808', 'name' => 'Unknown'],
            ['form_id' => 'HR2846', 'name' => 'Unknown'],
            ['form_id' => 'HR2857', 'name' => 'Unknown'],
            ['form_id' => 'HR2859', 'name' => 'Unknown'],
            ['form_id' => 'HR2860', 'name' => 'Unknown'],
            ['form_id' => 'HR2863B', 'name' => 'Unknown'],
            ['form_id' => 'HR2948', 'name' => 'Unknown'],
            ['form_id' => 'HR2992', 'name' => 'Unknown'],
            ['form_id' => 'HR3014', 'name' => 'Unknown'],
            ['form_id' => 'HR3030', 'name' => 'Unknown'],
            ['form_id' => 'HR3031', 'name' => 'Unknown'],
            ['form_id' => 'HR3045', 'name' => 'Unknown'],
            ['form_id' => 'HR3051', 'name' => 'Unknown'],
            ['form_id' => 'HR3073', 'name' => 'Unknown'],
            ['form_id' => 'HR3132', 'name' => 'Unknown'],
            ['form_id' => 'HR3136', 'name' => 'Unknown'],
            ['form_id' => 'HR3137', 'name' => 'Unknown'],
            ['form_id' => 'HR3161', 'name' => 'Unknown'],
            ['form_id' => 'HR3186', 'name' => 'Unknown'],
            ['form_id' => 'HR3201', 'name' => 'Unknown'],
            ['form_id' => 'HR3207A', 'name' => 'Unknown'],
            ['form_id' => 'HR3215', 'name' => 'Unknown'],
            ['form_id' => 'HR3221', 'name' => 'Unknown'],
            ['form_id' => 'HR3222', 'name' => 'Unknown'],
            ['form_id' => 'HR3223', 'name' => 'Unknown'],
            ['form_id' => 'HR3242', 'name' => 'Unknown'],
            ['form_id' => 'HR3243', 'name' => 'Unknown'],
            ['form_id' => 'HR3246', 'name' => 'Unknown'],
            ['form_id' => 'HR3247', 'name' => 'Unknown'],
            ['form_id' => 'HR3270', 'name' => 'Unknown'],
            ['form_id' => 'HR3272', 'name' => 'Unknown'],
            ['form_id' => 'HR3313', 'name' => 'Unknown'],
            ['form_id' => 'HR3333', 'name' => 'Unknown'],
            ['form_id' => 'HR3338', 'name' => 'Unknown'],
            ['form_id' => 'HR3339', 'name' => 'Unknown'],
            ['form_id' => 'HR3346', 'name' => 'Unknown'],
            ['form_id' => 'HR3467', 'name' => 'Unknown'],
            ['form_id' => 'HR3483', 'name' => 'Unknown'],
            ['form_id' => 'HR3486', 'name' => 'Unknown'],
            ['form_id' => 'HR3487', 'name' => 'Unknown'],
            ['form_id' => 'HR3493E', 'name' => 'Unknown'],
            ['form_id' => 'HR3494E', 'name' => 'Unknown'],
            ['form_id' => 'HR3495E', 'name' => 'Unknown'],
            ['form_id' => 'HR3496E', 'name' => 'Unknown'],
            ['form_id' => 'HR3497E', 'name' => 'Unknown'],
            ['form_id' => 'HR3498E', 'name' => 'Unknown'],
            ['form_id' => 'HR3507', 'name' => 'Unknown'],
            ['form_id' => 'HR3540', 'name' => 'Unknown'],
            ['form_id' => 'HR3550', 'name' => 'Unknown'],
            ['form_id' => 'HR3587', 'name' => 'Unknown'],
            ['form_id' => 'HR3588', 'name' => 'Unknown'],
            ['form_id' => 'HR3590', 'name' => 'Unknown'],
            ['form_id' => 'HR3593', 'name' => 'Unknown'],
            ['form_id' => 'HR3594', 'name' => 'Unknown'],
            ['form_id' => 'HR3596', 'name' => 'Unknown'],
            ['form_id' => 'HR3597', 'name' => 'Unknown'],
            ['form_id' => 'HR3623', 'name' => 'Unknown'],
            ['form_id' => 'HR3624E', 'name' => 'Unknown'],
            ['form_id' => 'HR3625E', 'name' => 'Unknown'],
            ['form_id' => 'HR3631', 'name' => 'Unknown'],
            ['form_id' => 'HR3632', 'name' => 'Unknown'],
            ['form_id' => 'HR3638', 'name' => 'Unknown'],
            ['form_id' => 'HR3645', 'name' => 'Unknown'],
            ['form_id' => 'HR3646', 'name' => 'Unknown'],
            ['form_id' => 'HR3648', 'name' => 'Unknown'],
            ['form_id' => 'HR3652', 'name' => 'Unknown'],
            ['form_id' => 'HR3656', 'name' => 'Unknown'],
            ['form_id' => 'HR3657E', 'name' => 'Unknown'],
            ['form_id' => 'HR3660', 'name' => 'Unknown'],
            ['form_id' => 'HR3661', 'name' => 'Unknown'],
            ['form_id' => 'HR3663', 'name' => 'Unknown'],
            ['form_id' => 'HR3664', 'name' => 'Unknown'],
            ['form_id' => 'HR3665', 'name' => 'Unknown'],
            ['form_id' => 'HR3666', 'name' => 'Unknown'],
            ['form_id' => 'HR3668', 'name' => 'Unknown'],
            ['form_id' => 'HR3668B', 'name' => 'Unknown'],
            ['form_id' => 'HR3673', 'name' => 'Unknown'],
            ['form_id' => 'HR3675', 'name' => 'Unknown'],
            ['form_id' => 'HR3676', 'name' => 'Unknown'],
            ['form_id' => 'HR3682', 'name' => 'Unknown'],
            ['form_id' => 'HR3683', 'name' => 'Unknown'],
            ['form_id' => 'HR3684', 'name' => 'Unknown'],
            ['form_id' => 'HR3719', 'name' => 'Unknown'],
            ['form_id' => 'HR3731', 'name' => 'Unknown'],
            ['form_id' => 'HR3732', 'name' => 'Unknown'],
            ['form_id' => 'HR3733', 'name' => 'Unknown'],
            ['form_id' => 'HR3734', 'name' => 'Unknown'],
            ['form_id' => 'HR4005', 'name' => 'Unknown'],
            ['form_id' => 'HR4006', 'name' => 'Unknown'],
            ['form_id' => 'HR4007', 'name' => 'Unknown'],
            ['form_id' => 'HR4009', 'name' => 'Unknown'],
            ['form_id' => 'HR4016', 'name' => 'Unknown'],
            ['form_id' => 'HR4027', 'name' => 'Unknown'],
            ['form_id' => 'HR4032', 'name' => 'Unknown'],
            ['form_id' => 'HR3655F', 'name' => 'Unknown'],
            ['form_id' => 'HR3697F', 'name' => 'Unknown'],
        ];

        foreach ($softwareSourceUpdates as $update) {
            $form = Form::where('form_id', $update['form_id'])->first();
            $source = FormSoftwareSource::where('name', $update['name'])->first();

            if ($form && $source) {
                DB::table('form_software_source_form')->insertOrIgnore([
                    'form_id' => $form->id,
                    'form_software_source_id' => $source->id,
                ]);
            } else {
                // Log a warning if a title in your spreadsheet doesn't match the DB
                if (!$form) {
                    Log::warning("BulkMetadataUpdateSeeder mismatch: Could not find Form '{$update['form_id']}'");
                }
                if (!$source) {
                    Log::warning("BulkMetadataUpdateSeeder mismatch: Could not find Software Source '{$update['name']}'");
                }
            }
        }

        // ========================================================================
        // 2. FORM LOCATION UPDATES
        // ========================================================================
        Log::warning("BulkMetadataUpdateSeeder: Beginning bulk update of form locations...");

        $formLocationUpdates = [
            ['form_id' => 'CF0149', 'name' => 'Unknown'],
            ['form_id' => 'CF2094', 'name' => 'Unknown'],
            ['form_id' => 'HR3689E', 'name' => 'ICM'],
            ['form_id' => 'CFL00540', 'name' => 'ICM'],
            ['form_id' => 'CFL00544', 'name' => 'ICM'],
            ['form_id' => 'HR3687E-AT', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATa', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATb', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATd', 'name' => 'Unknown'],
            ['form_id' => 'HR3691E - ATf', 'name' => 'Unknown'],
            ['form_id' => 'CF2447', 'name' => 'Unknown'],
            ['form_id' => 'CF0725', 'name' => 'Unknown'],
            ['form_id' => 'CF2601', 'name' => 'Unknown'],
            ['form_id' => 'CF2156', 'name' => 'ICM'],
            ['form_id' => 'CF2157', 'name' => 'ICM'],
            ['form_id' => 'CF4087', 'name' => 'ICM'],
            ['form_id' => 'CFL01015', 'name' => 'ICM'],
            ['form_id' => 'CFL01048', 'name' => 'ICM'],
            ['form_id' => 'CFL01071', 'name' => 'ICM'],
            ['form_id' => 'CFL01072', 'name' => 'ICM'],
            ['form_id' => 'CFL04556', 'name' => 'ICM'],
            ['form_id' => 'HR3655E', 'name' => 'Unknown'],
            ['form_id' => 'CF0605_portal', 'name' => 'Unknown'],
            ['form_id' => 'HR3492E', 'name' => 'Unknown'],
            ['form_id' => 'HR3600', 'name' => 'Unknown'],
            ['form_id' => 'HR3601E', 'name' => 'Unknown'],
            ['form_id' => 'HR3602', 'name' => 'Unknown'],
            ['form_id' => 'HR3603', 'name' => 'Unknown'],
            ['form_id' => 'HR3604', 'name' => 'Unknown'],
            ['form_id' => 'HR3605', 'name' => 'Unknown'],
            ['form_id' => 'HR3606', 'name' => 'Unknown'],
            ['form_id' => 'HR3607', 'name' => 'Unknown'],
            ['form_id' => 'HR3608', 'name' => 'Unknown'],
            ['form_id' => 'HR3609', 'name' => 'Unknown'],
            ['form_id' => 'HR3610', 'name' => 'Unknown'],
            ['form_id' => 'HR3611', 'name' => 'Unknown'],
            ['form_id' => 'HR3612', 'name' => 'Unknown'],
            ['form_id' => 'HR3613', 'name' => 'Unknown'],
            ['form_id' => 'HR3654E', 'name' => 'Unknown'],
            ['form_id' => 'HR3671', 'name' => 'Unknown'],
            ['form_id' => 'HR3711', 'name' => 'Unknown'],
            ['form_id' => 'HR3714E', 'name' => 'Unknown'],
            ['form_id' => 'MW-001', 'name' => 'Unknown'],
            ['form_id' => 'CF0620', 'name' => 'Unknown'],
            ['form_id' => 'CF3002', 'name' => 'Unknown'],
            ['form_id' => 'CF4182', 'name' => 'Unknown'],
            ['form_id' => 'CF4183', 'name' => 'Unknown'],
            ['form_id' => 'CF4184', 'name' => 'Unknown'],
            ['form_id' => 'CF4185', 'name' => 'Unknown'],
            ['form_id' => 'Sample Non-Interactive', 'name' => 'Unknown'],
            ['form_id' => 'CF0006', 'name' => 'Unknown'],
            ['form_id' => 'Bus Pass Renewal Application', 'name' => 'Unknown'],
            ['form_id' => 'CF0075', 'name' => 'Unknown'],
            ['form_id' => 'CF0247', 'name' => 'Unknown'],
            ['form_id' => 'CF0263', 'name' => 'Unknown'],
            ['form_id' => 'CF0270', 'name' => 'Unknown'],
            ['form_id' => 'CF0271', 'name' => 'Unknown'],
            ['form_id' => 'CF0328', 'name' => 'Unknown'],
            ['form_id' => 'CF0380', 'name' => 'Unknown'],
            ['form_id' => 'CF0381', 'name' => 'Unknown'],
            ['form_id' => 'CF0411A', 'name' => 'Unknown'],
            ['form_id' => 'CF0453', 'name' => 'Unknown'],
            ['form_id' => 'CF0603', 'name' => 'Unknown'],
            ['form_id' => 'CF0610', 'name' => 'Unknown'],
            ['form_id' => 'CF0635', 'name' => 'Unknown'],
            ['form_id' => 'CF0636', 'name' => 'Unknown'],
            ['form_id' => 'CF0637', 'name' => 'Unknown'],
            ['form_id' => 'CF0638', 'name' => 'Unknown'],
            ['form_id' => 'CF0639', 'name' => 'Unknown'],
            ['form_id' => 'CF0652', 'name' => 'Unknown'],
            ['form_id' => 'CF0654', 'name' => 'Unknown'],
            ['form_id' => 'CF0654A', 'name' => 'Unknown'],
            ['form_id' => 'CF0656', 'name' => 'Unknown'],
            ['form_id' => 'CF0660', 'name' => 'Unknown'],
            ['form_id' => 'CF0664', 'name' => 'Unknown'],
            ['form_id' => 'CF0666', 'name' => 'Unknown'],
            ['form_id' => 'CF0670', 'name' => 'Unknown'],
            ['form_id' => 'CF0673', 'name' => 'Unknown'],
            ['form_id' => 'CF0707', 'name' => 'Unknown'],
            ['form_id' => 'CF0708', 'name' => 'Unknown'],
            ['form_id' => 'CF0753', 'name' => 'Unknown'],
            ['form_id' => 'CF0754', 'name' => 'Unknown'],
            ['form_id' => 'CF0755', 'name' => 'Unknown'],
            ['form_id' => 'CF0756', 'name' => 'Unknown'],
            ['form_id' => 'CF0900', 'name' => 'Unknown'],
            ['form_id' => 'CF0902B', 'name' => 'Unknown'],
            ['form_id' => 'CF0903', 'name' => 'Unknown'],
            ['form_id' => 'CF0912', 'name' => 'Unknown'],
            ['form_id' => 'CF0927', 'name' => 'Unknown'],
            ['form_id' => 'CF0950', 'name' => 'Unknown'],
            ['form_id' => 'CF1001', 'name' => 'Unknown'],
            ['form_id' => 'CF1005', 'name' => 'Unknown'],
            ['form_id' => 'CF1005C', 'name' => 'Unknown'],
            ['form_id' => 'CF1036', 'name' => 'Unknown'],
            ['form_id' => 'CF1048', 'name' => 'Unknown'],
            ['form_id' => 'CF1054', 'name' => 'Unknown'],
            ['form_id' => 'CF1297', 'name' => 'Unknown'],
            ['form_id' => 'CF1298', 'name' => 'Unknown'],
            ['form_id' => 'CF1301', 'name' => 'Unknown'],
            ['form_id' => 'CF1304', 'name' => 'Unknown'],
            ['form_id' => 'CF1305', 'name' => 'Unknown'],
            ['form_id' => 'CF1305A', 'name' => 'Unknown'],
            ['form_id' => 'CF1305B', 'name' => 'Unknown'],
            ['form_id' => 'CF1305C', 'name' => 'Unknown'],
            ['form_id' => 'CF1305D', 'name' => 'Unknown'],
            ['form_id' => 'CF1306', 'name' => 'Unknown'],
            ['form_id' => 'CF1320', 'name' => 'Unknown'],
            ['form_id' => 'CF1320A', 'name' => 'Unknown'],
            ['form_id' => 'CF1321', 'name' => 'Unknown'],
            ['form_id' => 'CF1324', 'name' => 'Unknown'],
            ['form_id' => 'CF1326', 'name' => 'Unknown'],
            ['form_id' => 'CF1325a', 'name' => 'Unknown'],
            ['form_id' => 'CF1325b', 'name' => 'Unknown'],
            ['form_id' => 'CF1330', 'name' => 'Unknown'],
            ['form_id' => 'CF1331', 'name' => 'Unknown'],
            ['form_id' => 'CF1332', 'name' => 'Unknown'],
            ['form_id' => 'CF1335', 'name' => 'Unknown'],
            ['form_id' => 'CF1336', 'name' => 'Unknown'],
            ['form_id' => 'CF1345', 'name' => 'Unknown'],
            ['form_id' => 'CF1346', 'name' => 'Unknown'],
            ['form_id' => 'CF1369', 'name' => 'Unknown'],
            ['form_id' => 'CF1370', 'name' => 'Unknown'],
            ['form_id' => 'CF1371', 'name' => 'Unknown'],
            ['form_id' => 'CF1372', 'name' => 'Unknown'],
            ['form_id' => 'CF1470a', 'name' => 'Unknown'],
            ['form_id' => 'CF1470b', 'name' => 'Unknown'],
            ['form_id' => 'CF1703A', 'name' => 'Unknown'],
            ['form_id' => 'CF1704A', 'name' => 'Unknown'],
            ['form_id' => 'CF1706a', 'name' => 'Unknown'],
            ['form_id' => 'CF1706b', 'name' => 'Unknown'],
            ['form_id' => 'CF1900', 'name' => 'Unknown'],
            ['form_id' => 'CF1901', 'name' => 'Unknown'],
            ['form_id' => 'CF1902', 'name' => 'Unknown'],
            ['form_id' => 'CF1903', 'name' => 'Unknown'],
            ['form_id' => 'CF1904', 'name' => 'Unknown'],
            ['form_id' => 'CF1905', 'name' => 'Unknown'],
            ['form_id' => 'CF2002', 'name' => 'Unknown'],
            ['form_id' => 'CF2003', 'name' => 'Unknown'],
            ['form_id' => 'CF2004', 'name' => 'Unknown'],
            ['form_id' => 'CF2007', 'name' => 'Unknown'],
            ['form_id' => 'CF2040', 'name' => 'Unknown'],
            ['form_id' => 'CF2040A', 'name' => 'Unknown'],
            ['form_id' => 'CF2044A', 'name' => 'Unknown'],
            ['form_id' => 'CF2045', 'name' => 'Unknown'],
            ['form_id' => 'CF2185', 'name' => 'Unknown'],
            ['form_id' => 'CF2343', 'name' => 'Unknown'],
            ['form_id' => 'CF2512', 'name' => 'Unknown'],
            ['form_id' => 'CF2514', 'name' => 'Unknown'],
            ['form_id' => 'CF2515', 'name' => 'Unknown'],
            ['form_id' => 'CF2568', 'name' => 'Unknown'],
            ['form_id' => 'CF2600', 'name' => 'Unknown'],
            ['form_id' => 'CF2644', 'name' => 'Unknown'],
            ['form_id' => 'CF2655', 'name' => 'Unknown'],
            ['form_id' => 'CF2657', 'name' => 'Unknown'],
            ['form_id' => 'CF2657A', 'name' => 'Unknown'],
            ['form_id' => 'CF2657B', 'name' => 'Unknown'],
            ['form_id' => 'CF2657C', 'name' => 'Unknown'],
            ['form_id' => 'CF2671', 'name' => 'Unknown'],
            ['form_id' => 'CF2679', 'name' => 'Unknown'],
            ['form_id' => 'CF2682', 'name' => 'Unknown'],
            ['form_id' => 'CF2684', 'name' => 'Unknown'],
            ['form_id' => 'CF2685', 'name' => 'Unknown'],
            ['form_id' => 'CF2710', 'name' => 'Unknown'],
            ['form_id' => 'CF2723', 'name' => 'Unknown'],
            ['form_id' => 'CF2732', 'name' => 'Unknown'],
            ['form_id' => 'CF2734', 'name' => 'Unknown'],
            ['form_id' => 'CF2910A', 'name' => 'Unknown'],
            ['form_id' => 'CF2932', 'name' => 'Unknown'],
            ['form_id' => 'CF2960A', 'name' => 'Unknown'],
            ['form_id' => 'CF2961', 'name' => 'Unknown'],
            ['form_id' => 'CF2962', 'name' => 'Unknown'],
            ['form_id' => 'CF2963', 'name' => 'Unknown'],
            ['form_id' => 'CF3030', 'name' => 'Unknown'],
            ['form_id' => 'CF3501A', 'name' => 'Unknown'],
            ['form_id' => 'CF3700', 'name' => 'Unknown'],
            ['form_id' => 'CF4070', 'name' => 'Unknown'],
            ['form_id' => 'CF4071', 'name' => 'Unknown'],
            ['form_id' => 'CF4072', 'name' => 'Unknown'],
            ['form_id' => 'CF4076', 'name' => 'Unknown'],
            ['form_id' => 'CF4084', 'name' => 'Unknown'],
            ['form_id' => 'CF4085', 'name' => 'Unknown'],
            ['form_id' => 'CF4086', 'name' => 'Unknown'],
            ['form_id' => 'CF4092', 'name' => 'Unknown'],
            ['form_id' => 'CF4101', 'name' => 'Unknown'],
            ['form_id' => 'CF4102', 'name' => 'Unknown'],
            ['form_id' => 'CF4103', 'name' => 'Unknown'],
            ['form_id' => 'CF4104', 'name' => 'Unknown'],
            ['form_id' => 'CF4105', 'name' => 'Unknown'],
            ['form_id' => 'CF4106', 'name' => 'Unknown'],
            ['form_id' => 'CF4107', 'name' => 'Unknown'],
            ['form_id' => 'CF4108', 'name' => 'Unknown'],
            ['form_id' => 'CF4109', 'name' => 'Unknown'],
            ['form_id' => 'CF4110', 'name' => 'Unknown'],
            ['form_id' => 'CF4111', 'name' => 'Unknown'],
            ['form_id' => 'CF4114', 'name' => 'Unknown'],
            ['form_id' => 'CF4156', 'name' => 'Unknown'],
            ['form_id' => 'CF4160', 'name' => 'Unknown'],
            ['form_id' => 'CF4181', 'name' => 'Unknown'],
            ['form_id' => 'CF4112', 'name' => 'Unknown'],
            ['form_id' => 'CF4113', 'name' => 'Unknown'],
            ['form_id' => 'CF4144', 'name' => 'Unknown'],
            ['form_id' => 'CF4145', 'name' => 'Unknown'],
            ['form_id' => 'CF4146', 'name' => 'Unknown'],
            ['form_id' => 'CFL000001AA', 'name' => 'Unknown'],
            ['form_id' => 'CFL000010', 'name' => 'Unknown'],
            ['form_id' => 'CFL00010', 'name' => 'Unknown'],
            ['form_id' => 'CFL00543', 'name' => 'Unknown'],
            ['form_id' => 'CFL01023', 'name' => 'Unknown'],
            ['form_id' => 'CFL01024', 'name' => 'Unknown'],
            ['form_id' => 'CFL01025', 'name' => 'Unknown'],
            ['form_id' => 'CFL01026', 'name' => 'Unknown'],
            ['form_id' => 'CFL01027', 'name' => 'Unknown'],
            ['form_id' => 'CFL01028', 'name' => 'Unknown'],
            ['form_id' => 'CFL01029', 'name' => 'Unknown'],
            ['form_id' => 'CFL01030', 'name' => 'Unknown'],
            ['form_id' => 'CFL01031', 'name' => 'Unknown'],
            ['form_id' => 'CFL01032', 'name' => 'Unknown'],
            ['form_id' => 'CFL01033', 'name' => 'Unknown'],
            ['form_id' => 'CFL01034', 'name' => 'Unknown'],
            ['form_id' => 'CFL01035', 'name' => 'Unknown'],
            ['form_id' => 'CFL01036', 'name' => 'Unknown'],
            ['form_id' => 'CFL01049', 'name' => 'Unknown'],
            ['form_id' => 'CFL01050', 'name' => 'Unknown'],
            ['form_id' => 'CFL01051', 'name' => 'Unknown'],
            ['form_id' => 'CFL01052', 'name' => 'Unknown'],
            ['form_id' => 'CFL01053', 'name' => 'Unknown'],
            ['form_id' => 'CFL01054', 'name' => 'Unknown'],
            ['form_id' => 'CFL01055', 'name' => 'Unknown'],
            ['form_id' => 'CFL01056', 'name' => 'Unknown'],
            ['form_id' => 'CFL01057', 'name' => 'Unknown'],
            ['form_id' => 'CFL01058', 'name' => 'Unknown'],
            ['form_id' => 'CFL01059', 'name' => 'Unknown'],
            ['form_id' => 'CFL01060', 'name' => 'Unknown'],
            ['form_id' => 'CFL01061', 'name' => 'Unknown'],
            ['form_id' => 'CFL01062', 'name' => 'Unknown'],
            ['form_id' => 'CFL01063', 'name' => 'Unknown'],
            ['form_id' => 'CFL01064', 'name' => 'Unknown'],
            ['form_id' => 'CFL01065', 'name' => 'Unknown'],
            ['form_id' => 'CFL01066', 'name' => 'Unknown'],
            ['form_id' => 'CFL01067', 'name' => 'Unknown'],
            ['form_id' => 'CFL01068', 'name' => 'Unknown'],
            ['form_id' => 'CFL01069', 'name' => 'Unknown'],
            ['form_id' => 'CFL01070', 'name' => 'Unknown'],
            ['form_id' => 'CFL02015', 'name' => 'Unknown'],
            ['form_id' => 'CFL04555', 'name' => 'Unknown'],
            ['form_id' => 'CFL04557', 'name' => 'Unknown'],
            ['form_id' => 'CFL04558', 'name' => 'Unknown'],
            ['form_id' => 'CFL04559', 'name' => 'Unknown'],
            ['form_id' => 'HR0080P', 'name' => 'Unknown'],
            ['form_id' => 'HR3374E', 'name' => 'Unknown'],
            ['form_id' => 'HR3375E', 'name' => 'Unknown'],
            ['form_id' => 'Trauma Brief Screen', 'name' => 'Unknown'],
            ['form_id' => 'HR4029', 'name' => 'Unknown'],
            ['form_id' => 'CF0643', 'name' => 'Unknown'],
            ['form_id' => 'CF0911', 'name' => 'Unknown'],
            ['form_id' => 'CF3505', 'name' => 'Unknown'],
            ['form_id' => 'Coding Block', 'name' => 'Unknown'],
            ['form_id' => 'Petty Cash Reconciliation Replenishment Report', 'name' => 'Unknown'],
        ];

        foreach ($formLocationUpdates as $update) {
            $form = Form::where('form_id', $update['form_id'])->first();
            $location = FormLocation::where('name', $update['name'])->first();

            if ($form && $location) {
                DB::table('form_form_location')->insertOrIgnore([
                    'form_id' => $form->id,
                    'form_location_id' => $location->id,
                ]);
            } else {
                if (!$form) {
                    Log::warning("BulkMetadataUpdateSeeder mismatch: Could not find Form '{$update['form_id']}'");
                }
                if (!$location) {
                    Log::warning("BulkMetadataUpdateSeeder mismatch: Could not find Location '{$update['name']}'");
                }
            }
        }

        // ========================================================================
        // 3. USER TYPE UPDATES
        // ========================================================================

        Log::warning("BulkMetadataUpdateSeeder: Beginning bulk update of form user types...");

        $userTypeUpdates = [
            ['form_id' => 'CF0149', 'name' => 'Internal'],
            ['form_id' => 'CF2094', 'name' => 'Internal'],
            ['form_id' => 'HR3740E', 'name' => 'Internal'],
            ['form_id' => 'HR3740F', 'name' => 'Internal'],
            ['form_id' => 'HR3741', 'name' => 'Internal'],
            ['form_id' => 'HR3681', 'name' => 'Internal'],
            ['form_id' => 'HR3691F', 'name' => 'Internal'],
            ['form_id' => 'HR3704F', 'name' => 'Internal'],
            ['form_id' => 'HR4008', 'name' => 'Internal'],
            ['form_id' => 'HR4041', 'name' => 'Internal'],
            ['form_id' => 'HR4042', 'name' => 'Internal'],
            ['form_id' => 'T5007', 'name' => 'Internal'],
            ['form_id' => 'Decision Report Template', 'name' => 'Internal'],
            ['form_id' => 'CF2186', 'name' => 'Internal'],
            ['form_id' => 'CF0671', 'name' => 'Internal'],
            ['form_id' => 'CF0711', 'name' => 'Internal'],
            ['form_id' => 'CF1071', 'name' => 'Internal'],
            ['form_id' => 'CF1072', 'name' => 'Internal'],
            ['form_id' => 'CF2190', 'name' => 'Internal'],
            ['form_id' => 'CF4177', 'name' => 'Internal'],
            ['form_id' => 'CFDRT001', 'name' => 'Internal'],
            ['form_id' => 'CFL00514', 'name' => 'Internal'],
            ['form_id' => 'CFL01010', 'name' => 'Internal'],
            ['form_id' => 'CFL01013', 'name' => 'Internal'],
            ['form_id' => 'CFL01014', 'name' => 'Internal'],
            ['form_id' => 'CFL01016', 'name' => 'Internal'],
            ['form_id' => 'CFL01017', 'name' => 'Internal'],
            ['form_id' => 'CFL01018', 'name' => 'Internal'],
            ['form_id' => 'CFL01019', 'name' => 'Internal'],
            ['form_id' => 'CFL01021', 'name' => 'Internal'],
            ['form_id' => 'CFL01041', 'name' => 'Internal'],
            ['form_id' => 'CFL01042', 'name' => 'Internal'],
            ['form_id' => 'CFL02010', 'name' => 'Internal'],
            ['form_id' => 'CFL02012', 'name' => 'Internal'],
            ['form_id' => 'CFL02016', 'name' => 'Internal'],
            ['form_id' => 'CFL02019', 'name' => 'Internal'],
            ['form_id' => 'CFL02021', 'name' => 'Internal'],
            ['form_id' => 'CFL04510', 'name' => 'Internal'],
            ['form_id' => 'CFL04512', 'name' => 'Internal'],
            ['form_id' => 'CFL04515', 'name' => 'Internal'],
            ['form_id' => 'CFL04516', 'name' => 'Internal'],
            ['form_id' => 'CFL04520', 'name' => 'Internal'],
            ['form_id' => 'CFL04523', 'name' => 'Internal'],
            ['form_id' => 'CFL04524', 'name' => 'Internal'],
            ['form_id' => 'CFL04526', 'name' => 'Internal'],
            ['form_id' => 'CFL04527', 'name' => 'Internal'],
            ['form_id' => 'CFL04528', 'name' => 'Internal'],
            ['form_id' => 'CFL04529', 'name' => 'Internal'],
            ['form_id' => 'CFL04530', 'name' => 'Internal'],
            ['form_id' => 'CFL04533', 'name' => 'Internal'],
            ['form_id' => 'CFL04536', 'name' => 'Internal'],
            ['form_id' => 'CFL04541', 'name' => 'Internal'],
            ['form_id' => 'CFL04543', 'name' => 'Internal'],
            ['form_id' => 'CFL04554', 'name' => 'Internal'],
            ['form_id' => 'HR2848', 'name' => 'Internal'],
            ['form_id' => 'HR2865', 'name' => 'Internal'],
            ['form_id' => 'HR3460', 'name' => 'Internal'],
            ['form_id' => 'HR3461', 'name' => 'Internal'],
            ['form_id' => 'HR3462', 'name' => 'Internal'],
            ['form_id' => 'HR3464', 'name' => 'Internal'],
            ['form_id' => 'HR3466', 'name' => 'Internal'],
            ['form_id' => 'HR3504', 'name' => 'Internal'],
            ['form_id' => 'HR3627', 'name' => 'Internal'],
            ['form_id' => 'HR3628', 'name' => 'Internal'],
            ['form_id' => 'HR3629', 'name' => 'Internal'],
            ['form_id' => 'HR3630', 'name' => 'Internal'],
            ['form_id' => 'HR3688R', 'name' => 'Internal'],
            ['form_id' => 'HR3701E', 'name' => 'Internal'],
            ['form_id' => 'HR3702E', 'name' => 'Internal'],
            ['form_id' => 'NOA GST', 'name' => 'Internal'],
            ['form_id' => 'CF0025', 'name' => 'Internal'],
            ['form_id' => 'CF2511', 'name' => 'Internal'],
            ['form_id' => 'HR2916', 'name' => 'Internal'],
            ['form_id' => 'HR3503', 'name' => 'Internal'],
            ['form_id' => 'HR2892A', 'name' => 'Internal'],
            ['form_id' => 'HR3687E', 'name' => 'Internal'],
            ['form_id' => 'HR2384', 'name' => 'Internal'],
            ['form_id' => 'CF8787', 'name' => 'Internal'],
            ['form_id' => 'CF0640', 'name' => 'Internal'],
            ['form_id' => 'HR3234', 'name' => 'Internal'],
            ['form_id' => 'HR3689E', 'name' => 'Public'],
            ['form_id' => 'CFL00540', 'name' => 'Public'],
            ['form_id' => 'CFL00544', 'name' => 'Public'],
            ['form_id' => 'HR3687E-AT', 'name' => 'Public'],
            ['form_id' => 'HR3691E - ATa', 'name' => 'Public'],
            ['form_id' => 'HR3691E - ATb', 'name' => 'Public'],
            ['form_id' => 'HR3691E - ATd', 'name' => 'Public'],
            ['form_id' => 'HR3691E - ATf', 'name' => 'Public'],
            ['form_id' => 'CF2447', 'name' => 'Public'],
            ['form_id' => 'CF0725', 'name' => 'Public'],
            ['form_id' => 'CF2601', 'name' => 'Public'],
            ['form_id' => 'HR3260', 'name' => 'Public'],
            ['form_id' => 'HR3599', 'name' => 'Public'],
            ['form_id' => 'HR3219', 'name' => 'Public'],
            ['form_id' => 'HR3262', 'name' => 'Public'],
            ['form_id' => 'HR3534', 'name' => 'Public'],
            ['form_id' => 'HR3233', 'name' => 'Public'],
            ['form_id' => 'HR3236', 'name' => 'Public'],
            ['form_id' => 'HR3249', 'name' => 'Public'],
            ['form_id' => 'HR3334', 'name' => 'Public'],
            ['form_id' => 'HR3335', 'name' => 'Public'],
            ['form_id' => 'HR3555', 'name' => 'Public'],
            ['form_id' => 'HR3633', 'name' => 'Public'],
            ['form_id' => 'HR2247', 'name' => 'Public'],
            ['form_id' => 'HR2766', 'name' => 'Public'],
            ['form_id' => 'HR3352F', 'name' => 'Public'],
            ['form_id' => 'HR3353F', 'name' => 'Public'],
            ['form_id' => 'HR3354F', 'name' => 'Public'],
            ['form_id' => 'HR3355F', 'name' => 'Public'],
            ['form_id' => 'HR3356F', 'name' => 'Public'],
            ['form_id' => 'HR3357F', 'name' => 'Public'],
            ['form_id' => 'HR3358F', 'name' => 'Public'],
            ['form_id' => 'HR3360F', 'name' => 'Public'],
            ['form_id' => 'HR3361F', 'name' => 'Public'],
            ['form_id' => 'HR3362F', 'name' => 'Public'],
            ['form_id' => 'HR3363F', 'name' => 'Public'],
            ['form_id' => 'HR3364F', 'name' => 'Public'],
            ['form_id' => 'HR3365F', 'name' => 'Public'],
            ['form_id' => 'HR3366F', 'name' => 'Public'],
            ['form_id' => 'HR3367F', 'name' => 'Public'],
            ['form_id' => 'HR3368F', 'name' => 'Public'],
            ['form_id' => 'HR3369F', 'name' => 'Public'],
            ['form_id' => 'HR3370F', 'name' => 'Public'],
            ['form_id' => 'HR3372F', 'name' => 'Public'],
            ['form_id' => 'HR3376F', 'name' => 'Public'],
            ['form_id' => 'HR3379F', 'name' => 'Public'],
            ['form_id' => 'HR3380F', 'name' => 'Public'],
            ['form_id' => 'HR3381F', 'name' => 'Public'],
            ['form_id' => 'HR3382F', 'name' => 'Public'],
            ['form_id' => 'HR3383F', 'name' => 'Public'],
            ['form_id' => 'HR3384F', 'name' => 'Public'],
            ['form_id' => 'HR3385F', 'name' => 'Public'],
            ['form_id' => 'HR3386F', 'name' => 'Public'],
            ['form_id' => 'HR3387F', 'name' => 'Public'],
            ['form_id' => 'HR3388F', 'name' => 'Public'],
            ['form_id' => 'HR3389F', 'name' => 'Public'],
            ['form_id' => 'HR3390F', 'name' => 'Public'],
            ['form_id' => 'HR3391F', 'name' => 'Public'],
            ['form_id' => 'HR3392F', 'name' => 'Public'],
            ['form_id' => 'HR3393F', 'name' => 'Public'],
            ['form_id' => 'HR3394F', 'name' => 'Public'],
            ['form_id' => 'HR3396F', 'name' => 'Public'],
            ['form_id' => 'HR3397F', 'name' => 'Public'],
            ['form_id' => 'HR3398F', 'name' => 'Public'],
            ['form_id' => 'HR3399F', 'name' => 'Public'],
            ['form_id' => 'HR3400F', 'name' => 'Public'],
            ['form_id' => 'HR3450F', 'name' => 'Public'],
            ['form_id' => 'HR3451F', 'name' => 'Public'],
            ['form_id' => 'HR3452F', 'name' => 'Public'],
            ['form_id' => 'HR3453F', 'name' => 'Public'],
            ['form_id' => 'HR3454F', 'name' => 'Public'],
            ['form_id' => 'HR3455F', 'name' => 'Public'],
            ['form_id' => 'HR3456F', 'name' => 'Public'],
            ['form_id' => 'HR3458F', 'name' => 'Public'],
            ['form_id' => 'HR3459F', 'name' => 'Public'],
            ['form_id' => 'HR3484F', 'name' => 'Public'],
            ['form_id' => 'HR3688F', 'name' => 'Public'],
            ['form_id' => 'HR3692F', 'name' => 'Public'],
            ['form_id' => 'HR3693F', 'name' => 'Public'],
            ['form_id' => 'HR3694F', 'name' => 'Public'],
            ['form_id' => 'HR3695F', 'name' => 'Public'],
            ['form_id' => 'HR3696F', 'name' => 'Public'],
            ['form_id' => 'HR3698E-AT', 'name' => 'Public'],
            ['form_id' => 'HR3698F', 'name' => 'Public'],
            ['form_id' => 'HR3699F', 'name' => 'Public'],
            ['form_id' => 'HR3700F', 'name' => 'Public'],
            ['form_id' => 'HR3701F', 'name' => 'Public'],
            ['form_id' => 'HR3702F', 'name' => 'Public'],
            ['form_id' => 'HR3703F', 'name' => 'Public'],
            ['form_id' => 'HR3710F', 'name' => 'Public'],
            ['form_id' => 'CF1707', 'name' => 'Public'],
            ['form_id' => 'CF2602', 'name' => 'Public'],
            ['form_id' => 'CF4139', 'name' => 'Public'],
            ['form_id' => 'CF4141', 'name' => 'Public'],
            ['form_id' => 'vsa433', 'name' => 'Public'],
            ['form_id' => 'CF0700', 'name' => 'Public'],
            ['form_id' => 'CF0702', 'name' => 'Public'],
            ['form_id' => 'CF1234', 'name' => 'Public'],
            ['form_id' => 'CF1706', 'name' => 'Public'],
            ['form_id' => 'Bus Pass Replacement Application', 'name' => 'Public'],
            ['form_id' => 'HR0101', 'name' => 'Public'],
            ['form_id' => 'HR3235', 'name' => 'Public'],
            ['form_id' => 'HR2724', 'name' => 'Public'],
            ['form_id' => 'CF2595', 'name' => 'Public'],
            ['form_id' => 'CF2900', 'name' => 'Public'],
            ['form_id' => 'CFL01020', 'name' => 'Public'],
            ['form_id' => 'CFL00517', 'name' => 'Public'],
            ['form_id' => 'CFL00519', 'name' => 'Public'],
            ['form_id' => 'CFL00520', 'name' => 'Public'],
            ['form_id' => 'CFL00522', 'name' => 'Public'],
            ['form_id' => 'CFL00523', 'name' => 'Public'],
            ['form_id' => 'CFL00524', 'name' => 'Public'],
            ['form_id' => 'CFL00541', 'name' => 'Public'],
            ['form_id' => 'CFL00542', 'name' => 'Public'],
            ['form_id' => 'CFL00550', 'name' => 'Public'],
            ['form_id' => 'CFL01022', 'name' => 'Public'],
            ['form_id' => 'HR3700E', 'name' => 'Public'],
            ['form_id' => 'HR3704E', 'name' => 'Public'],
            ['form_id' => 'HR3710E', 'name' => 'Public'],
            ['form_id' => 'CF0035', 'name' => 'Public'],
            ['form_id' => 'CF0700A', 'name' => 'Public'],
            ['form_id' => 'CF0701', 'name' => 'Public'],
            ['form_id' => 'CF0711A', 'name' => 'Public'],
            ['form_id' => 'CF0711B', 'name' => 'Public'],
            ['form_id' => 'CF1630', 'name' => 'Public'],
            ['form_id' => 'CF2151', 'name' => 'Public'],
            ['form_id' => 'CF2159', 'name' => 'Public'],
            ['form_id' => 'CF2164', 'name' => 'Public'],
            ['form_id' => 'CF2201', 'name' => 'Public'],
            ['form_id' => 'CF2593', 'name' => 'Public'],
            ['form_id' => 'CF2615', 'name' => 'Public'],
            ['form_id' => 'CF2631', 'name' => 'Public'],
            ['form_id' => 'CF4051', 'name' => 'Public'],
            ['form_id' => 'CF0906', 'name' => 'Public'],
            ['form_id' => 'CF2933', 'name' => 'Public'],
            ['form_id' => 'CFL00516', 'name' => 'Public'],
            ['form_id' => 'CFL00518', 'name' => 'Public'],
            ['form_id' => 'CFL00521', 'name' => 'Public'],
            ['form_id' => 'CFL01040', 'name' => 'Public'],
            ['form_id' => 'CFL01043', 'name' => 'Public'],
            ['form_id' => 'CFL01044', 'name' => 'Public'],
            ['form_id' => 'CFL01045', 'name' => 'Public'],
            ['form_id' => 'CF0928', 'name' => 'Public'],
            ['form_id' => 'CF0929', 'name' => 'Public'],
            ['form_id' => 'CFL00510', 'name' => 'Public'],
            ['form_id' => 'CFL00511', 'name' => 'Public'],
            ['form_id' => 'CFL00513', 'name' => 'Public'],
            ['form_id' => 'CFL00515', 'name' => 'Public'],
            ['form_id' => 'HR3634', 'name' => 'Public'],
            ['form_id' => 'HR3637', 'name' => 'Public'],
            ['form_id' => 'HR3691E', 'name' => 'Public'],
            ['form_id' => 'HR3692E', 'name' => 'Public'],
            ['form_id' => 'HR3695AE', 'name' => 'Public'],
            ['form_id' => 'HR3696E', 'name' => 'Public'],
            ['form_id' => 'HR3690E', 'name' => 'Public'],
            ['form_id' => 'HR3690E-AT', 'name' => 'Public'],
            ['form_id' => 'HR3693E', 'name' => 'Public'],
            ['form_id' => 'HR3694E', 'name' => 'Public'],
            ['form_id' => 'HR3695E', 'name' => 'Public'],
            ['form_id' => 'HR3698E', 'name' => 'Public'],
            ['form_id' => 'HR3699E', 'name' => 'Public'],
            ['form_id' => 'HR3703E', 'name' => 'Public'],
            ['form_id' => 'HR3709E', 'name' => 'Public'],
            ['form_id' => 'HR0150A', 'name' => 'Public'],
            ['form_id' => 'HR0150B', 'name' => 'Public'],
            ['form_id' => 'HR2528', 'name' => 'Public'],
            ['form_id' => 'HR2949', 'name' => 'Public'],
            ['form_id' => 'HR3032', 'name' => 'Public'],
            ['form_id' => 'HR3138', 'name' => 'Public'],
            ['form_id' => 'HR3241', 'name' => 'Public'],
            ['form_id' => 'HR3245', 'name' => 'Public'],
            ['form_id' => 'HR3254', 'name' => 'Public'],
            ['form_id' => 'HR3344', 'name' => 'Public'],
            ['form_id' => 'HR3582', 'name' => 'Public'],
            ['form_id' => 'HR3583', 'name' => 'Public'],
            ['form_id' => 'HR3584', 'name' => 'Public'],
            ['form_id' => 'HR3585', 'name' => 'Public'],
            ['form_id' => 'HR2863', 'name' => 'Public'],
            ['form_id' => 'HR3162', 'name' => 'Public'],
            ['form_id' => 'HR3463', 'name' => 'Public'],
            ['form_id' => 'HR3189', 'name' => 'Public'],
            ['form_id' => 'HR3238', 'name' => 'Public'],
            ['form_id' => 'HR2894', 'name' => 'Public'],
            ['form_id' => 'HR3115', 'name' => 'Public'],
            ['form_id' => 'HR3320', 'name' => 'Public'],
            ['form_id' => 'HR2883', 'name' => 'Public'],
            ['form_id' => 'HR3043', 'name' => 'Public'],
            ['form_id' => 'HR0081', 'name' => 'Public'],
            ['form_id' => 'HR3371E', 'name' => 'Public'],
            ['form_id' => 'HR3375F', 'name' => 'Public'],
            ['form_id' => 'HR3687F', 'name' => 'Public'],
            ['form_id' => 'HR3689F', 'name' => 'Public'],
            ['form_id' => 'HR3690F', 'name' => 'Public'],
            ['form_id' => 'HR3709F', 'name' => 'Public'],
            ['form_id' => 'HR3689E-AT', 'name' => 'Public'],
            ['form_id' => 'CF1702A', 'name' => 'Public'],
            ['form_id' => 'CF1707A', 'name' => 'Public'],
            ['form_id' => 'CF1707B', 'name' => 'Public'],
            ['form_id' => 'CF0040', 'name' => 'Public'],
            ['form_id' => 'CF0042', 'name' => 'Public'],
            ['form_id' => 'CF0043', 'name' => 'Public'],
            ['form_id' => 'CF0044', 'name' => 'Public'],
            ['form_id' => 'CF0045', 'name' => 'Public'],
            ['form_id' => 'CF0046', 'name' => 'Public'],
            ['form_id' => 'CF0047', 'name' => 'Public'],
            ['form_id' => 'CF0048', 'name' => 'Public'],
            ['form_id' => 'CF2798', 'name' => 'Public'],
            ['form_id' => 'HR4025', 'name' => 'Public'],
        ];

        foreach ($userTypeUpdates as $update) {
            $form = Form::where('form_id', $update['form_id'])->first();
            $userType = UserType::where('name', $update['name'])->first();

            if ($form && $userType) {
                DB::table('form_user_type')->insertOrIgnore([
                    'form_id' => $form->id,
                    'user_type_id' => $userType->id,
                ]);
            } else {
                if (!$form) {
                    Log::warning("BulkMetadataUpdateSeeder mismatch: Could not find Form '{$update['form_id']}'");
                }
                if (!$userType) {
                    Log::warning("BulkMetadataUpdateSeeder mismatch: Could not find User Type '{$update['name']}'");
                }
            }
        }
    }
}