<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FormFormTagsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('form_form_tags')->truncate();

        DB::table('form_form_tags')->insert([
            ['form_id' => 7, 'form_tag_id' => 4],
            ['form_id' => 8, 'form_tag_id' => 4],
            ['form_id' => 9, 'form_tag_id' => 4],
            ['form_id' => 11, 'form_tag_id' => 4],
            ['form_id' => 19, 'form_tag_id' => 4],
            ['form_id' => 20, 'form_tag_id' => 4],
            ['form_id' => 21, 'form_tag_id' => 4],
            ['form_id' => 22, 'form_tag_id' => 4],
            ['form_id' => 35, 'form_tag_id' => 4],
            ['form_id' => 39, 'form_tag_id' => 4],
            ['form_id' => 41, 'form_tag_id' => 4],
            ['form_id' => 42, 'form_tag_id' => 5],
            ['form_id' => 42, 'form_tag_id' => 4],
            ['form_id' => 43, 'form_tag_id' => 3],
            ['form_id' => 43, 'form_tag_id' => 4],
            ['form_id' => 47, 'form_tag_id' => 4],
            ['form_id' => 48, 'form_tag_id' => 4],
            ['form_id' => 52, 'form_tag_id' => 3],
            ['form_id' => 52, 'form_tag_id' => 4],
            ['form_id' => 53, 'form_tag_id' => 3],
            ['form_id' => 54, 'form_tag_id' => 3],
            ['form_id' => 54, 'form_tag_id' => 4],
            ['form_id' => 55, 'form_tag_id' => 3],
            ['form_id' => 55, 'form_tag_id' => 4],
            ['form_id' => 56, 'form_tag_id' => 3],
            ['form_id' => 56, 'form_tag_id' => 4],
            ['form_id' => 57, 'form_tag_id' => 3],
            ['form_id' => 57, 'form_tag_id' => 4],
            ['form_id' => 58, 'form_tag_id' => 3],
            ['form_id' => 58, 'form_tag_id' => 4],
            ['form_id' => 59, 'form_tag_id' => 3],
            ['form_id' => 79, 'form_tag_id' => 1],
            ['form_id' => 80, 'form_tag_id' => 1],
            ['form_id' => 161, 'form_tag_id' => 5],
            ['form_id' => 173, 'form_tag_id' => 8],
            ['form_id' => 175, 'form_tag_id' => 7],
            ['form_id' => 178, 'form_tag_id' => 5],
            ['form_id' => 197, 'form_tag_id' => 5],
            ['form_id' => 231, 'form_tag_id' => 2],
            ['form_id' => 234, 'form_tag_id' => 2],
            ['form_id' => 236, 'form_tag_id' => 2],
            ['form_id' => 237, 'form_tag_id' => 2],
            ['form_id' => 238, 'form_tag_id' => 2],
            ['form_id' => 260, 'form_tag_id' => 1],
            ['form_id' => 260, 'form_tag_id' => 2],
            ['form_id' => 271, 'form_tag_id' => 2],
            ['form_id' => 407, 'form_tag_id' => 5],
            ['form_id' => 409, 'form_tag_id' => 5],
            ['form_id' => 427, 'form_tag_id' => 5],
            ['form_id' => 544, 'form_tag_id' => 5],
            ['form_id' => 548, 'form_tag_id' => 5],
            ['form_id' => 551, 'form_tag_id' => 4],
            ['form_id' => 553, 'form_tag_id' => 4],
            ['form_id' => 558, 'form_tag_id' => 5],
            ['form_id' => 560, 'form_tag_id' => 4],
            ['form_id' => 590, 'form_tag_id' => 4],
            ['form_id' => 591, 'form_tag_id' => 4],
            ['form_id' => 597, 'form_tag_id' => 5],
            ['form_id' => 654, 'form_tag_id' => 5],
            ['form_id' => 708, 'form_tag_id' => 4],
            ['form_id' => 712, 'form_tag_id' => 5],
            ['form_id' => 753, 'form_tag_id' => 5],
            ['form_id' => 754, 'form_tag_id' => 5],
            ['form_id' => 758, 'form_tag_id' => 5],
            ['form_id' => 760, 'form_tag_id' => 5],
            ['form_id' => 773, 'form_tag_id' => 4],
            ['form_id' => 800, 'form_tag_id' => 5],
            ['form_id' => 811, 'form_tag_id' => 5],
            ['form_id' => 816, 'form_tag_id' => 4],
            ['form_id' => 854, 'form_tag_id' => 4],
            ['form_id' => 855, 'form_tag_id' => 5],
            ['form_id' => 903, 'form_tag_id' => 3],
            ['form_id' => 903, 'form_tag_id' => 4],
            ['form_id' => 904, 'form_tag_id' => 3],
            ['form_id' => 904, 'form_tag_id' => 4],
            ['form_id' => 905, 'form_tag_id' => 3],
            ['form_id' => 906, 'form_tag_id' => 3],
            ['form_id' => 907, 'form_tag_id' => 3],
            ['form_id' => 908, 'form_tag_id' => 3],
            ['form_id' => 908, 'form_tag_id' => 4],
            ['form_id' => 909, 'form_tag_id' => 3],
            ['form_id' => 909, 'form_tag_id' => 4],
            ['form_id' => 912, 'form_tag_id' => 4],
            ['form_id' => 913, 'form_tag_id' => 4],
            ['form_id' => 983, 'form_tag_id' => 3],
            ['form_id' => 984, 'form_tag_id' => 3],
            ['form_id' => 985, 'form_tag_id' => 3],
            ['form_id' => 987, 'form_tag_id' => 3],
            ['form_id' => 987, 'form_tag_id' => 4],
            ['form_id' => 988, 'form_tag_id' => 3],
            ['form_id' => 988, 'form_tag_id' => 4],
            ['form_id' => 989, 'form_tag_id' => 3],
            ['form_id' => 990, 'form_tag_id' => 3],
            ['form_id' => 992, 'form_tag_id' => 3],
            ['form_id' => 1002, 'form_tag_id' => 3],
            ['form_id' => 1017, 'form_tag_id' => 1],
            ['form_id' => 1018, 'form_tag_id' => 1],
            ['form_id' => 1019, 'form_tag_id' => 1],
            ['form_id' => 1092, 'form_tag_id' => 5],
            ['form_id' => 1093, 'form_tag_id' => 5],
            ['form_id' => 1094, 'form_tag_id' => 5],
            ['form_id' => 1134, 'form_tag_id' => 5],
            ['form_id' => 1151, 'form_tag_id' => 5],
            ['form_id' => 1211, 'form_tag_id' => 7],
            ['form_id' => 1213, 'form_tag_id' => 7],
            ['form_id' => 1216, 'form_tag_id' => 7],
            ['form_id' => 1229, 'form_tag_id' => 5],
            ['form_id' => 1266, 'form_tag_id' => 1],
            ['form_id' => 1291, 'form_tag_id' => 7],
            ['form_id' => 1343, 'form_tag_id' => 2],
            ['form_id' => 1344, 'form_tag_id' => 2],
            ['form_id' => 1373, 'form_tag_id' => 2],
            ['form_id' => 1444, 'form_tag_id' => 2],
            ['form_id' => 1494, 'form_tag_id' => 7],
            ['form_id' => 1538, 'form_tag_id' => 2],
            ['form_id' => 1592, 'form_tag_id' => 1],
            ['form_id' => 1605, 'form_tag_id' => 2],
            ['form_id' => 1609, 'form_tag_id' => 2],
            ['form_id' => 1610, 'form_tag_id' => 2],
            ['form_id' => 1612, 'form_tag_id' => 2],
            ['form_id' => 1614, 'form_tag_id' => 2],
            ['form_id' => 1617, 'form_tag_id' => 2],
            ['form_id' => 1620, 'form_tag_id' => 2],
            ['form_id' => 1624, 'form_tag_id' => 2],
            ['form_id' => 1627, 'form_tag_id' => 2],
            ['form_id' => 1632, 'form_tag_id' => 2],
            ['form_id' => 1690, 'form_tag_id' => 1],
            ['form_id' => 1795, 'form_tag_id' => 1],
            ['form_id' => 1813, 'form_tag_id' => 2],
            ['form_id' => 1832, 'form_tag_id' => 2],
            ['form_id' => 1833, 'form_tag_id' => 2],
            ['form_id' => 1834, 'form_tag_id' => 2],
            ['form_id' => 1835, 'form_tag_id' => 2],
            ['form_id' => 1846, 'form_tag_id' => 2],
            ['form_id' => 1847, 'form_tag_id' => 2],
            ['form_id' => 1848, 'form_tag_id' => 2],
            ['form_id' => 1849, 'form_tag_id' => 2],
            ['form_id' => 1870, 'form_tag_id' => 1],
            ['form_id' => 1870, 'form_tag_id' => 2],
            ['form_id' => 1883, 'form_tag_id' => 2],
            ['form_id' => 1884, 'form_tag_id' => 2],
            ['form_id' => 1937, 'form_tag_id' => 6],
            ['form_id' => 1940, 'form_tag_id' => 6],
            ['form_id' => 1942, 'form_tag_id' => 6],
            ['form_id' => 1944, 'form_tag_id' => 6],
            ['form_id' => 1945, 'form_tag_id' => 6],
            ['form_id' => 1946, 'form_tag_id' => 6],
            ['form_id' => 1947, 'form_tag_id' => 6],
            ['form_id' => 1955, 'form_tag_id' => 6],
            ['form_id' => 1967, 'form_tag_id' => 6],
            ['form_id' => 2059, 'form_tag_id' => 7],
            ['form_id' => 2063, 'form_tag_id' => 5],
            ['form_id' => 2059, 'form_tag_id' => 7],
            ['form_id' => 2063, 'form_tag_id' => 5],
        ]);
    }
}
