version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    target-branch: "dev"
    versioning-strategy: "increase"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "laravel/framework"
        versions: ["^11.0"]
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    allow:
      - dependency-type: "security-updates"
      - dependency-type: "version-update:semver-major"
