version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    target-branch: "dev"
    ignore:
      - dependency-name: "laravel/framework"
        versions: ["^11.0"]
