apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-laravel-to-patroni
  namespace: ed84ea-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: patroni-cluster
      app.kubernetes.io/name: patroni
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: klamm-app
    ports:
    - protocol: TCP
      port: 5432