apiVersion: apps/v1
kind: Deployment
metadata:
  name: klamm-app
  labels:
    app.kubernetes.io/name: klamm-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: klamm-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klamm-app
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      initContainers:
        - name: setup-laravel-storage
          image: "{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting Laravel storage setup initContainer..."
              
              # Ensure proper ownership and permissions on the mounted shared storage volume.
              chown -R $(id -u):$(id -g) /var/www/storage || true
              chmod -R 775 /var/www/storage || true

              # Ensure the public web root is clean for the symlink
              # /var/www/html/public is the default document root for php:apache images,
              # and is mounted by public-html-volume emptyDir.
              rm -rf /var/www/html/public/storage # Remove any pre-existing symlink or directory
              
              # Create the symbolic link: public/storage -> storage/app/public
              # Based on the Klamm volume mounts:
              # symlink target: /var/www/storage/app/public (actual path on shared PVC)
              # symlink source: /var/www/html/public/storage (path in web server's docroot)
              echo "Creating symlink from /var/www/html/public/storage to /var/www/storage/app/public"
              php /var/www/html/artisan storage:link --force 

              echo "Laravel storage setup completed."
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/storage
            - name: public-html-volume
              mountPath: /var/www/html/public 
      containers:
        - name: klamm-app
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage-volume 
              mountPath: /var/www/storage
            - name: public-html-volume 
              mountPath: /var/www/html/public
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: klamm-cache-redis
                  key: redis-password
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: klamm-app-shared-pvc 
        - name: public-html-volume 
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: 600