apiVersion: apps/v1
kind: Deployment
metadata:
  name: klamm-app
  labels:
    app.kubernetes.io/name: klamm-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: klamm-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klamm-app
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      initContainers:
        - name: setup-laravel-storage
          image: "{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Use current UID and GID
              chown -R $(id -u):$(id -g) /var/www/storage || true
              chmod -R 775 /var/www/storage || true

              # Create needed subdirectories
              mkdir -p /var/www/storage/app/public || true
              mkdir -p /var/www/storage/framework/cache || true
              mkdir -p /var/www/storage/logs || true
              
              # Make sure public web root is clean for new symlink
              rm -rf /var/www/public/storage
              
              # Create the symbolic link: public/storage -> storage/app/public
              # Based on your volume mounts:
              # `public/storage` -> `/var/www/storage/app/public`
              # echo "Creating symlink from /var/www/html/public/storage to /var/www/storage/app/public"
              # php /var/www/html/artisan storage:link --force
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/storage
            - name: public-html-volume
              mountPath: /var/www/html/public
            # - name: form-data-volume
            #   mountPath: /var/www/storage/app/form_data
      containers:
        - name: klamm-app
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage-volume 
              mountPath: /var/www/storage
            # - name: form-data-volume 
            #   mountPath: /var/www/storage/app/form_data
            - name: public-html-volume
              mountPath: /var/www/html/public
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: klamm-cache-redis
                  key: redis-password
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: klamm-app-shared-pvc
        # - name: form-data-volume
        #   persistentVolumeClaim:
        #     claimName: klamm-form-data-pvc
        - name: public-html-volume
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: 600