apiVersion: apps/v1
kind: Deployment
metadata:
  name: klamm-queue-worker
  labels:
    app.kubernetes.io/name: klamm-queue-worker
spec:
  replicas: {{ .Values.queueWorker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: klamm-queue-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: klamm-queue-worker
    spec:
      containers:
        - name: queue-worker
          image: "{{ .Values.image.tag }}"
          command: ["php", "/var/www/artisan", "queue:work", "--sleep=3", "--tries=3", "--timeout=3600"]
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: klamm-cache-redis
                  key: redis-password
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/storage
            - name: form-data-volume
              mountPath: /var/www/storage/app/form_data
          resources:
            limits:
              cpu: {{ .Values.queueWorker.resources.limits.cpu }}
              memory: {{ .Values.queueWorker.resources.limits.memory }}
            requests:
              cpu: {{ .Values.queueWorker.resources.requests.cpu }}
              memory: {{ .Values.queueWorker.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: klamm-app-shared-pvc
        - name: form-data-volume
          persistentVolumeClaim:
            claimName: klamm-form-data-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: 600
