apiVersion: v1
kind: Service
metadata:
  name: reverb-service
  labels:
    app.kubernetes.io/name: reverb-service
spec:
  selector:
    app.kubernetes.io/name: klamm-reverb-worker
  ports:
    - name: reverb
      protocol: TCP
      port: 6001
      targetPort: 6001
