apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: klamm-app
  labels:
    app.kubernetes.io/name: klamm-app
spec:
  to:
    kind: Service
    name: klamm-app
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
