-- Package Body: Anonymization Data: Job Titles
-- Synthetic job titles
-- Data Count: 639

CREATE OR REPLACE PACKAGE BODY ANON_DATA.PKG_ANON_JOB_TITLES AS

  -- Data array type
  TYPE T_ANON_JOB_TITLES IS TABLE OF VARCHAR2(75) INDEX BY PLS_INTEGER;

  -- Embedded data
  g_data T_ANON_JOB_TITLES;
  C_COUNT CONSTANT NUMBER := 639;

  -- Initialize data array
  PROCEDURE init_data IS
  BEGIN
    g_data(1) := 'Academic librarian';
    g_data(2) := 'Accommodation manager';
    g_data(3) := 'Accountant, chartered';
    g_data(4) := 'Accountant, chartered certified';
    g_data(5) := 'Accountant, chartered management';
    g_data(6) := 'Accountant, chartered public finance';
    g_data(7) := 'Accounting technician';
    g_data(8) := 'Actor';
    g_data(9) := 'Actuary';
    g_data(10) := 'Acupuncturist';
    g_data(11) := 'Administrator';
    g_data(12) := 'Administrator, Civil Service';
    g_data(13) := 'Administrator, arts';
    g_data(14) := 'Administrator, charities/voluntary organisations';
    g_data(15) := 'Administrator, education';
    g_data(16) := 'Administrator, local government';
    g_data(17) := 'Administrator, sports';
    g_data(18) := 'Adult guidance worker';
    g_data(19) := 'Adult nurse';
    g_data(20) := 'Advertising account executive';
    g_data(21) := 'Advertising account planner';
    g_data(22) := 'Advertising art director';
    g_data(23) := 'Advertising copywriter';
    g_data(24) := 'Advice worker';
    g_data(25) := 'Aeronautical engineer';
    g_data(26) := 'Agricultural consultant';
    g_data(27) := 'Agricultural engineer';
    g_data(28) := 'Aid worker';
    g_data(29) := 'Air broker';
    g_data(30) := 'Air cabin crew';
    g_data(31) := 'Air traffic controller';
    g_data(32) := 'Airline pilot';
    g_data(33) := 'Ambulance person';
    g_data(34) := 'Amenity horticulturist';
    g_data(35) := 'Analytical chemist';
    g_data(36) := 'Animal nutritionist';
    g_data(37) := 'Animal technologist';
    g_data(38) := 'Animator';
    g_data(39) := 'Applications developer';
    g_data(40) := 'Arboriculturist';
    g_data(41) := 'Archaeologist';
    g_data(42) := 'Architect';
    g_data(43) := 'Architectural technologist';
    g_data(44) := 'Archivist';
    g_data(45) := 'Armed forces logistics/support/administrative officer';
    g_data(46) := 'Armed forces operational officer';
    g_data(47) := 'Armed forces technical officer';
    g_data(48) := 'Armed forces training and education officer';
    g_data(49) := 'Art gallery manager';
    g_data(50) := 'Art therapist';
    g_data(51) := 'Artist';
    g_data(52) := 'Arts administrator';
    g_data(53) := 'Arts development officer';
    g_data(54) := 'Associate Professor';
    g_data(55) := 'Astronomer';
    g_data(56) := 'Audiological scientist';
    g_data(57) := 'Automotive engineer';
    g_data(58) := 'Banker';
    g_data(59) := 'Barista';
    g_data(60) := 'Barrister';
    g_data(61) := 'Barrister''s clerk';
    g_data(62) := 'Best boy';
    g_data(63) := 'Biochemist, clinical';
    g_data(64) := 'Biomedical engineer';
    g_data(65) := 'Biomedical scientist';
    g_data(66) := 'Bonds trader';
    g_data(67) := 'Bookseller';
    g_data(68) := 'Brewing technologist';
    g_data(69) := 'Broadcast engineer';
    g_data(70) := 'Broadcast journalist';
    g_data(71) := 'Broadcast presenter';
    g_data(72) := 'Building control surveyor';
    g_data(73) := 'Building services engineer';
    g_data(74) := 'Building surveyor';
    g_data(75) := 'Buyer, industrial';
    g_data(76) := 'Buyer, retail';
    g_data(77) := 'Cabin crew';
    g_data(78) := 'Call centre manager';
    g_data(79) := 'Camera operator';
    g_data(80) := 'Careers adviser';
    g_data(81) := 'Careers information officer';
    g_data(82) := 'Cartographer';
    g_data(83) := 'Catering manager';
    g_data(84) := 'Ceramics designer';
    g_data(85) := 'Charity fundraiser';
    g_data(86) := 'Charity officer';
    g_data(87) := 'Chartered accountant';
    g_data(88) := 'Chartered certified accountant';
    g_data(89) := 'Chartered legal executive (England and Wales)';
    g_data(90) := 'Chartered loss adjuster';
    g_data(91) := 'Chartered management accountant';
    g_data(92) := 'Chartered public finance accountant';
    g_data(93) := 'Chemical engineer';
    g_data(94) := 'Chemist, analytical';
    g_data(95) := 'Chief Executive Officer';
    g_data(96) := 'Chief Financial Officer';
    g_data(97) := 'Chief Marketing Officer';
    g_data(98) := 'Chief Operating Officer';
    g_data(99) := 'Chief Strategy Officer';
    g_data(100) := 'Chief Technology Officer';
  END;

  PROCEDURE init_data_2 IS
  BEGIN
    g_data(101) := 'Chief of Staff';
    g_data(102) := 'Child psychotherapist';
    g_data(103) := 'Chiropodist';
    g_data(104) := 'Chiropractor';
    g_data(105) := 'Civil Service administrator';
    g_data(106) := 'Civil Service fast streamer';
    g_data(107) := 'Civil engineer, consulting';
    g_data(108) := 'Civil engineer, contracting';
    g_data(109) := 'Claims inspector/assessor';
    g_data(110) := 'Clinical biochemist';
    g_data(111) := 'Clinical cytogeneticist';
    g_data(112) := 'Clinical embryologist';
    g_data(113) := 'Clinical molecular geneticist';
    g_data(114) := 'Clinical psychologist';
    g_data(115) := 'Clinical research associate';
    g_data(116) := 'Clinical scientist, histocompatibility and immunogenetics';
    g_data(117) := 'Clothing/textile technologist';
    g_data(118) := 'Colour technologist';
    g_data(119) := 'Commercial art gallery manager';
    g_data(120) := 'Commercial horticulturist';
    g_data(121) := 'Commercial/residential surveyor';
    g_data(122) := 'Commissioning editor';
    g_data(123) := 'Communications engineer';
    g_data(124) := 'Community arts worker';
    g_data(125) := 'Community development worker';
    g_data(126) := 'Community education officer';
    g_data(127) := 'Community pharmacist';
    g_data(128) := 'Company secretary';
    g_data(129) := 'Comptroller';
    g_data(130) := 'Computer games developer';
    g_data(131) := 'Conference centre manager';
    g_data(132) := 'Conservation officer, historic buildings';
    g_data(133) := 'Conservation officer, nature';
    g_data(134) := 'Conservator, furniture';
    g_data(135) := 'Conservator, museum/gallery';
    g_data(136) := 'Consulting civil engineer';
    g_data(137) := 'Contracting civil engineer';
    g_data(138) := 'Contractor';
    g_data(139) := 'Control and instrumentation engineer';
    g_data(140) := 'Copy';
    g_data(141) := 'Copywriter, advertising';
    g_data(142) := 'Corporate investment banker';
    g_data(143) := 'Corporate treasurer';
    g_data(144) := 'Counselling psychologist';
    g_data(145) := 'Counsellor';
    g_data(146) := 'Curator';
    g_data(147) := 'Customer service manager';
    g_data(148) := 'Cytogeneticist';
    g_data(149) := 'Dance movement psychotherapist';
    g_data(150) := 'Dancer';
    g_data(151) := 'Data processing manager';
    g_data(152) := 'Data scientist';
    g_data(153) := 'Database administrator';
    g_data(154) := 'Dealer';
    g_data(155) := 'Dentist';
    g_data(156) := 'Designer, blown glass/stained glass';
    g_data(157) := 'Designer, ceramics/pottery';
    g_data(158) := 'Designer, exhibition/display';
    g_data(159) := 'Designer, fashion/clothing';
    g_data(160) := 'Designer, furniture';
    g_data(161) := 'Designer, graphic';
    g_data(162) := 'Designer, industrial/product';
    g_data(163) := 'Designer, interior/spatial';
    g_data(164) := 'Designer, jewellery';
    g_data(165) := 'Designer, multimedia';
    g_data(166) := 'Designer, television/film set';
    g_data(167) := 'Designer, textile';
    g_data(168) := 'Development worker, community';
    g_data(169) := 'Development worker, international aid';
    g_data(170) := 'Diagnostic radiographer';
    g_data(171) := 'Dietitian';
    g_data(172) := 'Diplomatic Services operational officer';
    g_data(173) := 'Dispensing optician';
    g_data(174) := 'Doctor, general practice';
    g_data(175) := 'Doctor, hospital';
    g_data(176) := 'Dramatherapist';
    g_data(177) := 'Drilling engineer';
    g_data(178) := 'Early years teacher';
    g_data(179) := 'Ecologist';
    g_data(180) := 'Economist';
    g_data(181) := 'Editor, commissioning';
    g_data(182) := 'Editor, film/video';
    g_data(183) := 'Editor, magazine features';
    g_data(184) := 'Editorial assistant';
    g_data(185) := 'Education administrator';
    g_data(186) := 'Education officer, community';
    g_data(187) := 'Education officer, environmental';
    g_data(188) := 'Education officer, museum';
    g_data(189) := 'Educational psychologist';
    g_data(190) := 'Electrical engineer';
    g_data(191) := 'Electronics engineer';
    g_data(192) := 'Embryologist, clinical';
    g_data(193) := 'Emergency planning/management officer';
    g_data(194) := 'Energy engineer';
    g_data(195) := 'Energy manager';
    g_data(196) := 'Engineer, aeronautical';
    g_data(197) := 'Engineer, agricultural';
    g_data(198) := 'Engineer, automotive';
    g_data(199) := 'Engineer, biomedical';
    g_data(200) := 'Engineer, broadcasting (operations)';
  END;

  PROCEDURE init_data_3 IS
  BEGIN
    g_data(201) := 'Engineer, building services';
    g_data(202) := 'Engineer, chemical';
    g_data(203) := 'Engineer, civil (consulting)';
    g_data(204) := 'Engineer, civil (contracting)';
    g_data(205) := 'Engineer, communications';
    g_data(206) := 'Engineer, control and instrumentation';
    g_data(207) := 'Engineer, drilling';
    g_data(208) := 'Engineer, electrical';
    g_data(209) := 'Engineer, electronics';
    g_data(210) := 'Engineer, energy';
    g_data(211) := 'Engineer, land';
    g_data(212) := 'Engineer, maintenance';
    g_data(213) := 'Engineer, maintenance (IT)';
    g_data(214) := 'Engineer, manufacturing';
    g_data(215) := 'Engineer, manufacturing systems';
    g_data(216) := 'Engineer, materials';
    g_data(217) := 'Engineer, mining';
    g_data(218) := 'Engineer, petroleum';
    g_data(219) := 'Engineer, production';
    g_data(220) := 'Engineer, site';
    g_data(221) := 'Engineer, structural';
    g_data(222) := 'Engineer, technical sales';
    g_data(223) := 'Engineer, water';
    g_data(224) := 'Engineering geologist';
    g_data(225) := 'English as a foreign language teacher';
    g_data(226) := 'English as a second language teacher';
    g_data(227) := 'Environmental consultant';
    g_data(228) := 'Environmental education officer';
    g_data(229) := 'Environmental health practitioner';
    g_data(230) := 'Environmental manager';
    g_data(231) := 'Equality and diversity officer';
    g_data(232) := 'Equities trader';
    g_data(233) := 'Ergonomist';
    g_data(234) := 'Estate agent';
    g_data(235) := 'Estate manager/land agent';
    g_data(236) := 'Event organiser';
    g_data(237) := 'Exercise physiologist';
    g_data(238) := 'Exhibition designer';
    g_data(239) := 'Exhibitions officer, museum/gallery';
    g_data(240) := 'Facilities manager';
    g_data(241) := 'Farm manager';
    g_data(242) := 'Fashion designer';
    g_data(243) := 'Fast food restaurant manager';
    g_data(244) := 'Field seismologist';
    g_data(245) := 'Field trials officer';
    g_data(246) := 'Film/video editor';
    g_data(247) := 'Financial adviser';
    g_data(248) := 'Financial controller';
    g_data(249) := 'Financial manager';
    g_data(250) := 'Financial planner';
    g_data(251) := 'Financial risk analyst';
    g_data(252) := 'Financial trader';
    g_data(253) := 'Fine artist';
    g_data(254) := 'Firefighter';
    g_data(255) := 'Fish farm manager';
    g_data(256) := 'Fisheries officer';
    g_data(257) := 'Fitness centre manager';
    g_data(258) := 'Food technologist';
    g_data(259) := 'Forensic psychologist';
    g_data(260) := 'Forensic scientist';
    g_data(261) := 'Forest/woodland manager';
    g_data(262) := 'Freight forwarder';
    g_data(263) := 'Furniture conservator/restorer';
    g_data(264) := 'Furniture designer';
    g_data(265) := 'Further education lecturer';
    g_data(266) := 'Futures trader';
    g_data(267) := 'Gaffer';
    g_data(268) := 'Games developer';
    g_data(269) := 'Garment/textile technologist';
    g_data(270) := 'General practice doctor';
    g_data(271) := 'Geneticist, molecular';
    g_data(272) := 'Geochemist';
    g_data(273) := 'Geographical information systems officer';
    g_data(274) := 'Geologist, engineering';
    g_data(275) := 'Geologist, wellsite';
    g_data(276) := 'Geophysical data processor';
    g_data(277) := 'Geophysicist/field seismologist';
    g_data(278) := 'Geoscientist';
    g_data(279) := 'Glass blower/designer';
    g_data(280) := 'Government social research officer';
    g_data(281) := 'Graphic designer';
    g_data(282) := 'Haematologist';
    g_data(283) := 'Health and safety adviser';
    g_data(284) := 'Health and safety inspector';
    g_data(285) := 'Health physicist';
    g_data(286) := 'Health promotion specialist';
    g_data(287) := 'Health service manager';
    g_data(288) := 'Health visitor';
    g_data(289) := 'Herbalist';
    g_data(290) := 'Heritage manager';
    g_data(291) := 'Herpetologist';
    g_data(292) := 'Higher education careers adviser';
    g_data(293) := 'Higher education lecturer';
    g_data(294) := 'Historic buildings inspector/conservation officer';
    g_data(295) := 'Holiday representative';
    g_data(296) := 'Homeopath';
    g_data(297) := 'Horticultural consultant';
    g_data(298) := 'Horticultural therapist';
    g_data(299) := 'Horticulturist, amenity';
    g_data(300) := 'Horticulturist, commercial';
  END;

  PROCEDURE init_data_4 IS
  BEGIN
    g_data(301) := 'Hospital doctor';
    g_data(302) := 'Hospital pharmacist';
    g_data(303) := 'Hotel manager';
    g_data(304) := 'Housing manager/officer';
    g_data(305) := 'Human resources officer';
    g_data(306) := 'Hydrogeologist';
    g_data(307) := 'Hydrographic surveyor';
    g_data(308) := 'Hydrologist';
    g_data(309) := 'IT consultant';
    g_data(310) := 'IT sales professional';
    g_data(311) := 'IT technical support officer';
    g_data(312) := 'IT trainer';
    g_data(313) := 'Illustrator';
    g_data(314) := 'Immigration officer';
    g_data(315) := 'Immunologist';
    g_data(316) := 'Industrial buyer';
    g_data(317) := 'Industrial/product designer';
    g_data(318) := 'Information officer';
    g_data(319) := 'Information systems manager';
    g_data(320) := 'Insurance account manager';
    g_data(321) := 'Insurance broker';
    g_data(322) := 'Insurance claims handler';
    g_data(323) := 'Insurance risk surveyor';
    g_data(324) := 'Insurance underwriter';
    g_data(325) := 'Intelligence analyst';
    g_data(326) := 'Interior and spatial designer';
    g_data(327) := 'International aid/development worker';
    g_data(328) := 'Interpreter';
    g_data(329) := 'Investment analyst';
    g_data(330) := 'Investment banker, corporate';
    g_data(331) := 'Investment banker, operational';
    g_data(332) := 'Jewellery designer';
    g_data(333) := 'Journalist, broadcasting';
    g_data(334) := 'Journalist, magazine';
    g_data(335) := 'Journalist, newspaper';
    g_data(336) := 'Land';
    g_data(337) := 'Land/geomatics surveyor';
    g_data(338) := 'Landscape architect';
    g_data(339) := 'Lawyer';
    g_data(340) := 'Learning disability nurse';
    g_data(341) := 'Learning mentor';
    g_data(342) := 'Lecturer, further education';
    g_data(343) := 'Lecturer, higher education';
    g_data(344) := 'Legal executive';
    g_data(345) := 'Legal secretary';
    g_data(346) := 'Leisure centre manager';
    g_data(347) := 'Lexicographer';
    g_data(348) := 'Librarian, academic';
    g_data(349) := 'Librarian, public';
    g_data(350) := 'Licensed conveyancer';
    g_data(351) := 'Lighting technician, broadcasting/film/video';
    g_data(352) := 'Lobbyist';
    g_data(353) := 'Local government officer';
    g_data(354) := 'Location manager';
    g_data(355) := 'Logistics and distribution manager';
    g_data(356) := 'Loss adjuster, chartered';
    g_data(357) := 'Magazine features editor';
    g_data(358) := 'Magazine journalist';
    g_data(359) := 'Maintenance engineer';
    g_data(360) := 'Make';
    g_data(361) := 'Management consultant';
    g_data(362) := 'Manufacturing engineer';
    g_data(363) := 'Manufacturing systems engineer';
    g_data(364) := 'Marine scientist';
    g_data(365) := 'Market researcher';
    g_data(366) := 'Marketing executive';
    g_data(367) := 'Materials engineer';
    g_data(368) := 'Mechanical engineer';
    g_data(369) := 'Media buyer';
    g_data(370) := 'Media planner';
    g_data(371) := 'Medical illustrator';
    g_data(372) := 'Medical laboratory scientific officer';
    g_data(373) := 'Medical physicist';
    g_data(374) := 'Medical sales representative';
    g_data(375) := 'Medical secretary';
    g_data(376) := 'Medical technical officer';
    g_data(377) := 'Mental health nurse';
    g_data(378) := 'Merchandiser, retail';
    g_data(379) := 'Merchant navy officer';
    g_data(380) := 'Metallurgist';
    g_data(381) := 'Meteorologist';
    g_data(382) := 'Microbiologist';
    g_data(383) := 'Midwife';
    g_data(384) := 'Minerals surveyor';
    g_data(385) := 'Mining engineer';
    g_data(386) := 'Mudlogger';
    g_data(387) := 'Multimedia programmer';
    g_data(388) := 'Multimedia specialist';
    g_data(389) := 'Museum education officer';
    g_data(390) := 'Museum/gallery conservator';
    g_data(391) := 'Museum/gallery curator';
    g_data(392) := 'Museum/gallery exhibitions officer';
    g_data(393) := 'Music therapist';
    g_data(394) := 'Music tutor';
    g_data(395) := 'Musician';
    g_data(396) := 'Nature conservation officer';
    g_data(397) := 'Naval architect';
    g_data(398) := 'Network engineer';
    g_data(399) := 'Neurosurgeon';
    g_data(400) := 'Newspaper journalist';
  END;

  PROCEDURE init_data_5 IS
  BEGIN
    g_data(401) := 'Nurse, adult';
    g_data(402) := 'Nurse, children''s';
    g_data(403) := 'Nurse, learning disability';
    g_data(404) := 'Nurse, mental health';
    g_data(405) := 'Nutritional therapist';
    g_data(406) := 'Occupational hygienist';
    g_data(407) := 'Occupational psychologist';
    g_data(408) := 'Occupational therapist';
    g_data(409) := 'Oceanographer';
    g_data(410) := 'Office manager';
    g_data(411) := 'Oncologist';
    g_data(412) := 'Operational investment banker';
    g_data(413) := 'Operational researcher';
    g_data(414) := 'Operations geologist';
    g_data(415) := 'Ophthalmologist';
    g_data(416) := 'Optician, dispensing';
    g_data(417) := 'Optometrist';
    g_data(418) := 'Orthoptist';
    g_data(419) := 'Osteopath';
    g_data(420) := 'Outdoor activities/education manager';
    g_data(421) := 'Paediatric nurse';
    g_data(422) := 'Paramedic';
    g_data(423) := 'Passenger transport manager';
    g_data(424) := 'Patent attorney';
    g_data(425) := 'Patent examiner';
    g_data(426) := 'Pathologist';
    g_data(427) := 'Pension scheme manager';
    g_data(428) := 'Pensions consultant';
    g_data(429) := 'Personal assistant';
    g_data(430) := 'Personnel officer';
    g_data(431) := 'Petroleum engineer';
    g_data(432) := 'Pharmacist, community';
    g_data(433) := 'Pharmacist, hospital';
    g_data(434) := 'Pharmacologist';
    g_data(435) := 'Photographer';
    g_data(436) := 'Physicist, medical';
    g_data(437) := 'Physiological scientist';
    g_data(438) := 'Physiotherapist';
    g_data(439) := 'Phytotherapist';
    g_data(440) := 'Pilot, airline';
    g_data(441) := 'Planning and development surveyor';
    g_data(442) := 'Plant breeder/geneticist';
    g_data(443) := 'Podiatrist';
    g_data(444) := 'Police officer';
    g_data(445) := 'Politician''s assistant';
    g_data(446) := 'Presenter, broadcasting';
    g_data(447) := 'Press photographer';
    g_data(448) := 'Press sub';
    g_data(449) := 'Primary school teacher';
    g_data(450) := 'Print production planner';
    g_data(451) := 'Printmaker';
    g_data(452) := 'Prison officer';
    g_data(453) := 'Private music teacher';
    g_data(454) := 'Probation officer';
    g_data(455) := 'Producer, radio';
    g_data(456) := 'Producer, television/film/video';
    g_data(457) := 'Product designer';
    g_data(458) := 'Product manager';
    g_data(459) := 'Product/process development scientist';
    g_data(460) := 'Production assistant, radio';
    g_data(461) := 'Production assistant, television';
    g_data(462) := 'Production designer, theatre/television/film';
    g_data(463) := 'Production engineer';
    g_data(464) := 'Production manager';
    g_data(465) := 'Professor Emeritus';
    g_data(466) := 'Programme researcher, broadcasting/film/video';
    g_data(467) := 'Programmer, applications';
    g_data(468) := 'Programmer, multimedia';
    g_data(469) := 'Programmer, systems';
    g_data(470) := 'Proofreader';
    g_data(471) := 'Psychiatric nurse';
    g_data(472) := 'Psychiatrist';
    g_data(473) := 'Psychologist, clinical';
    g_data(474) := 'Psychologist, counselling';
    g_data(475) := 'Psychologist, educational';
    g_data(476) := 'Psychologist, forensic';
    g_data(477) := 'Psychologist, occupational';
    g_data(478) := 'Psychologist, prison and probation services';
    g_data(479) := 'Psychologist, sport and exercise';
    g_data(480) := 'Psychotherapist';
    g_data(481) := 'Psychotherapist, child';
    g_data(482) := 'Psychotherapist, dance movement';
    g_data(483) := 'Public affairs consultant';
    g_data(484) := 'Public house manager';
    g_data(485) := 'Public librarian';
    g_data(486) := 'Public relations account executive';
    g_data(487) := 'Public relations officer';
    g_data(488) := 'Publishing copy';
    g_data(489) := 'Publishing rights manager';
    g_data(490) := 'Purchasing manager';
    g_data(491) := 'Quality manager';
    g_data(492) := 'Quantity surveyor';
    g_data(493) := 'Quarry manager';
    g_data(494) := 'Race relations officer';
    g_data(495) := 'Radiation protection practitioner';
    g_data(496) := 'Radio broadcast assistant';
    g_data(497) := 'Radio producer';
    g_data(498) := 'Radiographer, diagnostic';
    g_data(499) := 'Radiographer, therapeutic';
    g_data(500) := 'Ranger/warden';
  END;

  PROCEDURE init_data_6 IS
  BEGIN
    g_data(501) := 'Records manager';
    g_data(502) := 'Recruitment consultant';
    g_data(503) := 'Recycling officer';
    g_data(504) := 'Regulatory affairs officer';
    g_data(505) := 'Research officer, government';
    g_data(506) := 'Research officer, political party';
    g_data(507) := 'Research officer, trade union';
    g_data(508) := 'Research scientist (life sciences)';
    g_data(509) := 'Research scientist (maths)';
    g_data(510) := 'Research scientist (medical)';
    g_data(511) := 'Research scientist (physical sciences)';
    g_data(512) := 'Restaurant manager';
    g_data(513) := 'Restaurant manager, fast food';
    g_data(514) := 'Retail banker';
    g_data(515) := 'Retail buyer';
    g_data(516) := 'Retail manager';
    g_data(517) := 'Retail merchandiser';
    g_data(518) := 'Risk analyst';
    g_data(519) := 'Risk manager';
    g_data(520) := 'Runner, broadcasting/film/video';
    g_data(521) := 'Rural practice surveyor';
    g_data(522) := 'Sales executive';
    g_data(523) := 'Sales professional, IT';
    g_data(524) := 'Sales promotion account executive';
    g_data(525) := 'Science writer';
    g_data(526) := 'Scientific laboratory technician';
    g_data(527) := 'Scientist, audiological';
    g_data(528) := 'Scientist, biomedical';
    g_data(529) := 'Scientist, clinical (histocompatibility and immunogenetics)';
    g_data(530) := 'Scientist, forensic';
    g_data(531) := 'Scientist, marine';
    g_data(532) := 'Scientist, physiological';
    g_data(533) := 'Scientist, product/process development';
    g_data(534) := 'Scientist, research (life sciences)';
    g_data(535) := 'Scientist, research (maths)';
    g_data(536) := 'Scientist, research (medical)';
    g_data(537) := 'Scientist, research (physical sciences)';
    g_data(538) := 'Scientist, water quality';
    g_data(539) := 'Secondary school teacher';
    g_data(540) := 'Secretary, company';
    g_data(541) := 'Secretary/administrator';
    g_data(542) := 'Seismic interpreter';
    g_data(543) := 'Senior tax professional/tax inspector';
    g_data(544) := 'Set designer';
    g_data(545) := 'Ship broker';
    g_data(546) := 'Site engineer';
    g_data(547) := 'Social research officer, government';
    g_data(548) := 'Social researcher';
    g_data(549) := 'Social worker';
    g_data(550) := 'Software engineer';
    g_data(551) := 'Soil scientist';
    g_data(552) := 'Solicitor';
    g_data(553) := 'Solicitor, Scotland';
    g_data(554) := 'Sound technician, broadcasting/film/video';
    g_data(555) := 'Special educational needs teacher';
    g_data(556) := 'Special effects artist';
    g_data(557) := 'Speech and language therapist';
    g_data(558) := 'Sport and exercise psychologist';
    g_data(559) := 'Sports administrator';
    g_data(560) := 'Sports coach';
    g_data(561) := 'Sports development officer';
    g_data(562) := 'Sports therapist';
    g_data(563) := 'Stage manager';
    g_data(564) := 'Statistician';
    g_data(565) := 'Structural engineer';
    g_data(566) := 'Sub';
    g_data(567) := 'Surgeon';
    g_data(568) := 'Surveyor, building';
    g_data(569) := 'Surveyor, building control';
    g_data(570) := 'Surveyor, commercial/residential';
    g_data(571) := 'Surveyor, hydrographic';
    g_data(572) := 'Surveyor, insurance';
    g_data(573) := 'Surveyor, land/geomatics';
    g_data(574) := 'Surveyor, minerals';
    g_data(575) := 'Surveyor, mining';
    g_data(576) := 'Surveyor, planning and development';
    g_data(577) := 'Surveyor, quantity';
    g_data(578) := 'Surveyor, rural practice';
    g_data(579) := 'Systems analyst';
    g_data(580) := 'Systems developer';
    g_data(581) := 'TEFL teacher';
    g_data(582) := 'Tax adviser';
    g_data(583) := 'Tax inspector';
    g_data(584) := 'Teacher, English as a foreign language';
    g_data(585) := 'Teacher, adult education';
    g_data(586) := 'Teacher, early years/pre';
    g_data(587) := 'Teacher, music';
    g_data(588) := 'Teacher, primary school';
    g_data(589) := 'Teacher, secondary school';
    g_data(590) := 'Teacher, special educational needs';
    g_data(591) := 'Teaching laboratory technician';
    g_data(592) := 'Technical author';
    g_data(593) := 'Technical brewer';
    g_data(594) := 'Technical sales engineer';
    g_data(595) := 'Telecommunications researcher';
    g_data(596) := 'Television camera operator';
    g_data(597) := 'Television floor manager';
    g_data(598) := 'Television production assistant';
    g_data(599) := 'Television/film/video producer';
    g_data(600) := 'Textile designer';
  END;

  PROCEDURE init_data_7 IS
  BEGIN
    g_data(601) := 'Theatre director';
    g_data(602) := 'Theatre manager';
    g_data(603) := 'Theatre stage manager';
    g_data(604) := 'Theme park manager';
    g_data(605) := 'Therapeutic radiographer';
    g_data(606) := 'Therapist, art';
    g_data(607) := 'Therapist, drama';
    g_data(608) := 'Therapist, horticultural';
    g_data(609) := 'Therapist, music';
    g_data(610) := 'Therapist, nutritional';
    g_data(611) := 'Therapist, occupational';
    g_data(612) := 'Therapist, speech and language';
    g_data(613) := 'Therapist, sports';
    g_data(614) := 'Tour manager';
    g_data(615) := 'Tourism officer';
    g_data(616) := 'Tourist information centre manager';
    g_data(617) := 'Town planner';
    g_data(618) := 'Toxicologist';
    g_data(619) := 'Trade mark attorney';
    g_data(620) := 'Trade union research officer';
    g_data(621) := 'Trading standards officer';
    g_data(622) := 'Training and development officer';
    g_data(623) := 'Translator';
    g_data(624) := 'Transport planner';
    g_data(625) := 'Travel agency manager';
    g_data(626) := 'Tree surgeon';
    g_data(627) := 'Veterinary surgeon';
    g_data(628) := 'Video editor';
    g_data(629) := 'Visual merchandiser';
    g_data(630) := 'Volunteer coordinator';
    g_data(631) := 'Warden/ranger';
    g_data(632) := 'Warehouse manager';
    g_data(633) := 'Waste management officer';
    g_data(634) := 'Water engineer';
    g_data(635) := 'Water quality scientist';
    g_data(636) := 'Web designer';
    g_data(637) := 'Wellsite geologist';
    g_data(638) := 'Writer';
    g_data(639) := 'Youth worker';
  END;

  -- Deterministic lookup by seed
  FUNCTION GET_JOB_TITLES(
    p_seed IN VARCHAR2,
    p_max_len IN NUMBER DEFAULT 75
  ) RETURN VARCHAR2 DETERMINISTIC IS
    v_hash RAW(32);
    v_idx NUMBER;
  BEGIN
    v_hash := DBMS_CRYPTO.HASH(
      UTL_RAW.CAST_TO_RAW(NVL(p_seed, 'NULL')),
      DBMS_CRYPTO.HASH_SH256
    );
    v_idx := MOD(TO_NUMBER(SUBSTR(RAWTOHEX(v_hash), 1, 8), 'XXXXXXXX'), C_COUNT) + 1;
    RETURN SUBSTR(g_data(v_idx), 1, LEAST(p_max_len, 75));
  END GET_JOB_TITLES;

  -- Random lookup (non-deterministic)
  FUNCTION GET_JOB_TITLES_RANDOM(
    p_max_len IN NUMBER DEFAULT 75
  ) RETURN VARCHAR2 IS
    v_idx NUMBER;
  BEGIN
    v_idx := TRUNC(DBMS_RANDOM.VALUE(1, C_COUNT + 1));
    RETURN SUBSTR(g_data(v_idx), 1, LEAST(p_max_len, 75));
  END GET_JOB_TITLES_RANDOM;

  -- Index-based lookup
  FUNCTION GET_JOB_TITLES_BY_INDEX(
    p_index IN NUMBER,
    p_max_len IN NUMBER DEFAULT 75
  ) RETURN VARCHAR2 DETERMINISTIC IS
    v_idx NUMBER;
  BEGIN
    v_idx := MOD(ABS(NVL(p_index, 0)), C_COUNT) + 1;
    RETURN SUBSTR(g_data(v_idx), 1, LEAST(p_max_len, 75));
  END GET_JOB_TITLES_BY_INDEX;

  -- Count function
  FUNCTION GET_COUNT RETURN NUMBER DETERMINISTIC IS
  BEGIN
    RETURN C_COUNT;
  END GET_COUNT;

BEGIN
  -- Initialize data on package load
  init_data;
  init_data_2;
  init_data_3;
  init_data_4;
  init_data_5;
  init_data_6;
  init_data_7;
END PKG_ANON_JOB_TITLES;
/