replicaCount: 1

image:
  repository: ghcr.io/kiiskila-bcgov/klamm
  pullPolicy: Always
  tag: "dev"

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

pvc:
  storage: "100Mi"
