replicaCount: 1

revisionHistoryLimit: 3

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

image:
  repository: ghcr.io/bcgov/klamm
  pullPolicy: Always
  tag: "dev"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

queueWorker:
  replicaCount: 1
  resources:
    limits:
      cpu: "50m"
      memory: "128Mi"
    requests:
      cpu: "25m"
      memory: "64Mi"

reverbWorker:
  replicaCount: 1
  resources:
    limits:
      cpu: "50m"
      memory: "128Mi"
    requests:
      cpu: "25m"
      memory: "64Mi"

pvc:
  storage: "100Mi"
  formData:
    storage: "100Mi"

db:
  host: "patroni-cluster"
  port: 5432
  name: "app"
  username: "app"
  password: "<app-db-password>"
