replicaCount: 1

image:
  repository: ghcr.io/kiiskila-bcgov/klamm
  pullPolicy: Always
  tag: "dev"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

pvc:
  storage: "100Mi"

db:
  host: "patroni-cluster"
  port: 5432
  name: "app"
  username: "app"
  password: "<app-db-password>"
