replicaCount: 1

revisionHistoryLimit: 3

image:
  repository: ghcr.io/bcgov/klamm
  pullPolicy: Always
  tag: "dev"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

queueWorker:
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

pvc:
  storage: "100Mi"

db:
  host: "patroni-cluster"
  port: 5432
  name: "app"
  username: "app"
  password: "<app-db-password>"
