name: Deploy to OpenShift

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prints test message
      run: echo "Testing GitHub Actions permissions"
