name: External Kiln Deployment Monitor
on:
  push:
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  TARGET_REPO: bcgov/kiln
  HELM_CHART_PATH: helm
  DEPLOYMENT_NAME: kiln
  # Specify the Kiln version tag to deploy - currently using dev tag
  KILN_VERSION_TAG: dev
  # Ensure this matches exactly what's in the Kiln repository
  IMAGE_NAME: bcgov/kiln

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    environment: tools
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout Kiln repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.KILN_VERSION_TAG }}
          path: kiln-source

      - name: Setup OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Authenticate with OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ vars.OPENSHIFT_SERVER }}
          namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true

      - name: Helm Deployment
        run: |
          helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ./kiln-source/${{ env.HELM_CHART_PATH }} \
            --set image.tag="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.KILN_VERSION_TAG }}" \
            --debug
